project_id = "betternotes-v2"

[db.seed]
enabled = true
sql_paths = ["./seed/seed.sql"]

[functions.create-checkout-session]
verify_jwt = true

[functions.create-portal-session]
verify_jwt = true

[functions.create-job]
verify_jwt = true

[functions.dispatch-queued-jobs]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
