/**
 * latex-parser.ts
 * Manual (regex + split) parser for LaTeX source generated by BetterNotes templates.
 * No external parsing libraries — intentionally lightweight for F3-M1 PoC.
 *
 * Supported block types:
 *   section        — \section{}, \section*{}, \subsection{}, \subsection*{}, \subsubsection{}
 *   formula-block  — $$...$$, \[...\], \begin{equation}..., \begin{align*}..., etc.
 *   formula-inline — $...$ within paragraph text
 *   table          — \begin{tabular}...\end{tabular}
 *   list           — \begin{itemize}...\end{itemize}, \begin{enumerate}...\end{enumerate}
 *   paragraph      — everything else (plain text with possible inline math)
 */

export type BlockType =
  | 'section'
  | 'chapter'
  | 'cover'
  | 'formula-block'
  | 'formula-inline'
  | 'table'
  | 'list'
  | 'paragraph'
  | 'hr'
  | 'box'
  | 'page-header'
  | 'col-start'
  | 'col-end';

export type BoxSubtype =
  | 'definition'
  | 'theorem'
  | 'proposition'
  | 'observation'
  | 'example'
  | 'lemma'
  | 'corollary'
  | 'remark'
  | 'proof'
  | 'workedexample'
  | 'keypoint'
  | 'warning'
  | 'summary';

export interface Block {
  id: string;
  type: BlockType;
  latex_source: string;
  /** section level: 1 = \section, 2 = \subsection, 3 = \subsubsection */
  level?: number;
  /** For type === 'box': the theorem-like environment that produced this block */
  boxSubtype?: BoxSubtype;
  /** Optional label for box/chapter/section (e.g. \begin{definition}[Label] ...) */
  label?: string;
  /** For type === 'cover': extracted document metadata */
  title?: string;
  author?: string;
  date?: string;
  /** For type === 'chapter': auto-assigned sequential number (filled by viewer) */
  chapterNumber?: number;
  /** Cornell-style margin cue shown in the wide left margin */
  cue?: string;
  /** For type === 'page-header': extracted fancyhdr left/right content */
  headerLeft?: string;
  headerRight?: string;
  /** Character offset in the original source where this block starts (after preamble strip) */
  sourceStart?: number;
  /** Character offset in the original source where this block ends (exclusive) */
  sourceEnd?: number;
}

export interface ParseOptions {
  /**
   * When true (or when template is 'lecture_notes'), top-level \section commands
   * are rendered as chapters to match the PDF's report-class output.
   */
  templateId?: string;
}

// ─── helpers ─────────────────────────────────────────────────────────────────

let _idCounter = 0;
function makeId(prefix: string): string {
  return `${prefix}-${++_idCounter}`;
}

const CLEAN3_TITLE_MARKER = '__BN_CLEAN3_TITLE__';
const CLEAN3_SUB_MARKER = '__BN_CLEAN3_SUB__';

function stripLatexComments(text: string): string {
  return text
    .split('\n')
    .map((line) => {
      let out = '';
      let escaped = false;
      for (let i = 0; i < line.length; i++) {
        const ch = line[i];
        if (ch === '%' && !escaped) break;
        out += ch;
        escaped = ch === '\\' && !escaped;
      }
      return out;
    })
    .join('\n');
}

function sanitizeMarkerText(raw: string): string {
  return raw
    .replace(/\\text(?:bf|it)\{([^}]*)\}/g, '$1')
    .replace(/\\emph\{([^}]*)\}/g, '$1')
    .replace(/\\[a-zA-Z]+\*?(?:\[[^\]]*\])?\{([^}]*)\}/g, '$1')
    .replace(/\\([#$%&_{}])/g, '$1')
    .replace(/\\[a-zA-Z]+\*?\b/g, '')
    .replace(/[{}]/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

function preprocessClean3TitleBar(text: string): string {
  let out = text;
  const vspaceMarker = '\\vspace{4pt}';
  const startMarker = '\\noindent\\colorbox{headerblue}';

  while (true) {
    const start = out.indexOf(startMarker);
    if (start === -1) break;
    const endVspace = out.indexOf(vspaceMarker, start);
    if (endVspace === -1) break;
    const end = endVspace + vspaceMarker.length;
    const chunk = out.slice(start, end);

    const titleMatch = chunk.match(
      /\\centering\s*\{\s*\\Large\\bfseries\\color\{white\}\s*([\s\S]*?)\}\s*\\\\\s*\[[^\]]*\]/
    );
    if (!titleMatch) break;
    const subtitleMatch = chunk.match(/\{\s*\\small\\color\{white!85\}\s*([\s\S]*?)\s*\}/);

    const title = sanitizeMarkerText(titleMatch[1]);
    const subtitle = sanitizeMarkerText(subtitleMatch?.[1] ?? '');
    const syntheticSection = `\\section{${CLEAN3_TITLE_MARKER}${title}${CLEAN3_SUB_MARKER}${subtitle}}`;

    out = `${out.slice(0, start)}\n${syntheticSection}\n${out.slice(end)}`;
  }

  return out;
}

/**
 * Extract the balanced content inside \begin{env}...\end{env}.
 * Returns [fullMatch, innerContent] or null.
 */
function extractEnv(
  source: string,
  env: string,
  startIndex = 0
): { full: string; inner: string; start: number; end: number } | null {
  const openTag = `\\begin{${env}}`;
  const closeTag = `\\end{${env}}`;
  const start = source.indexOf(openTag, startIndex);
  if (start === -1) return null;
  const end = source.indexOf(closeTag, start + openTag.length);
  if (end === -1) return null;
  return {
    full: source.slice(start, end + closeTag.length),
    inner: source.slice(start + openTag.length, end),
    start,
    end: end + closeTag.length,
  };
}

// ─── strip LaTeX preamble/document wrapper ────────────────────────────────────

/**
 * Remove everything before \begin{document} and after \end{document},
 * and also strip the \begin{document} / \end{document} tags themselves.
 * If no \begin{document} found, return the whole source as-is.
 */
function stripPreamble(source: string): string {
  const beginDoc = source.indexOf('\\begin{document}');
  const endDoc = source.indexOf('\\end{document}');
  if (beginDoc === -1) return source;
  const inner = source.slice(beginDoc + '\\begin{document}'.length, endDoc === -1 ? undefined : endDoc);
  return inner;
}

// ─── cover metadata extraction ────────────────────────────────────────────────

/** Extract a balanced {...} argument following a \command. Returns null if not found. */
function extractCommandArg(source: string, command: string): { value: string; start: number; end: number } | null {
  const re = new RegExp(`\\\\${command}\\s*\\{`, 'g');
  const m = re.exec(source);
  if (!m) return null;
  const argStart = m.index + m[0].length - 1; // position of the opening brace
  const arg = extractBracedArg(source, argStart);
  if (!arg) return null;
  return { value: arg.content.trim(), start: m.index, end: arg.end };
}

/** Clean a LaTeX-ish value for display (strip commands, braces, line breaks). */
function cleanMetadataValue(raw: string): string {
  return raw
    .replace(/\\today\b/g, new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }))
    .replace(/\\LaTeX\b/g, 'LaTeX')
    .replace(/\\TeX\b/g, 'TeX')
    .replace(/\\\\/g, ' ')
    .replace(/\\[a-zA-Z]+\*?\{([^}]*)\}/g, '$1')
    .replace(/\\[a-zA-Z]+\*?\b/g, '')
    .replace(/[{}]/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

function cleanPlainLatexText(raw: string): string {
  return raw
    .replace(/\\text(?:bf|it)\{([^}]*)\}/g, '$1')
    .replace(/\\emph\{([^}]*)\}/g, '$1')
    .replace(/\\textcolor\{[^}]*\}\{([^}]*)\}/g, '$1')
    .replace(/\\(?:footnotesize|scriptsize|small|large|Large|LARGE|huge|Huge|normalsize)\b/g, '')
    .replace(/\\[a-zA-Z]+\*?(?:\[[^\]]*\])?\{([^}]*)\}/g, '$1')
    .replace(/\\([#$%&_{}])/g, '$1')
    .replace(/[{}]/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

/**
 * Scan the source for \title{...}, \author{...}, \date{...}. If any metadata is
 * found, return the extracted values plus a version of the source with those
 * commands (and \maketitle, \begin{titlepage}...\end{titlepage}) removed.
 */
function extractCoverMetadata(source: string): {
  title: string | null;
  author: string | null;
  date: string | null;
  stripped: string;
  hadMakeTitle: boolean;
} {
  let stripped = source;

  const titleMatch = extractCommandArg(stripped, 'title');
  const authorMatch = extractCommandArg(stripped, 'author');
  const dateMatch = extractCommandArg(stripped, 'date');

  // Remove \title{...}, \author{...}, \date{...}
  for (const match of [titleMatch, authorMatch, dateMatch]) {
    if (match) {
      stripped = stripped.slice(0, match.start) + stripped.slice(match.end);
    }
  }

  // Re-scan offsets after first pass would be wrong. Reset and remove by regex (simpler).
  stripped = source
    .replace(/\\title\s*\{(?:[^{}]|\{[^{}]*\})*\}/g, '')
    .replace(/\\author\s*\{(?:[^{}]|\{[^{}]*\})*\}/g, '')
    .replace(/\\date\s*\{(?:[^{}]|\{[^{}]*\})*\}/g, '');

  // Remove \maketitle and \begin{titlepage}...\end{titlepage}
  const hadMakeTitle = /\\maketitle\b/.test(stripped) || /\\begin\{titlepage\}/.test(stripped);
  stripped = stripped
    .replace(/\\maketitle\b/g, '')
    .replace(/\\begin\{titlepage\}[\s\S]*?\\end\{titlepage\}/g, '');

  // Also drop a leading \tableofcontents (the Interactive cover includes an implicit TOC visual)
  stripped = stripped.replace(/\\tableofcontents\b/g, '');

  return {
    title: titleMatch ? cleanMetadataValue(titleMatch.value) : null,
    author: authorMatch ? cleanMetadataValue(authorMatch.value) : null,
    date: dateMatch ? cleanMetadataValue(dateMatch.value) : null,
    stripped,
    hadMakeTitle,
  };
}

// ─── block-level environment extraction ──────────────────────────────────────

const BLOCK_ENVS = [
  // math environments
  'equation', 'equation*', 'align', 'align*', 'alignat', 'alignat*',
  'gather', 'gather*', 'multline', 'multline*', 'flalign', 'flalign*',
  'eqnarray', 'eqnarray*',
  // table
  'tabular', 'tabular*', 'tabularx', 'longtable', 'array',
  // list
  'itemize', 'enumerate', 'description',
  // theorem-like (from templates)
  'definition', 'theorem', 'lemma', 'proposition', 'corollary', 'remark',
  'proof', 'obs', 'observation', 'example', 'example*', 'exercise*',
  // tcolorbox environments (lecture_notes template)
  'workedexample', 'keypoint', 'warning',
  // multicol (study_form, 2cols_portrait, landscape_3col_maths)
  'multicols', 'multicols*',
  // alignment/text wrappers
  'flushright', 'flushleft', 'center',
  // other common
  'figure', 'table', 'minipage', 'abstract', 'verbatim',
] as const;

const MATH_ENVS = new Set([
  'equation', 'equation*', 'align', 'align*', 'alignat', 'alignat*',
  'gather', 'gather*', 'multline', 'multline*', 'flalign', 'flalign*',
  'eqnarray', 'eqnarray*',
]);

const LIST_ENVS = new Set(['itemize', 'enumerate', 'description']);

const TABLE_ENVS = new Set(['tabular', 'tabular*', 'tabularx', 'longtable', 'array']);

// ─── section extractor ────────────────────────────────────────────────────────

const SECTION_RE = /\\(chapter|subsubsection|subsection|section)\*?\{([^}]*)\}/g;

function extractSectionInfo(raw: string): { title: string; level: number; kind: 'chapter' | 'section' } {
  const m = /\\(chapter|subsubsection|subsection|section)\*?\{([^}]*)\}/.exec(raw);
  if (!m) return { title: raw, level: 1, kind: 'section' };
  const cmd = m[1];
  if (cmd === 'chapter') return { title: m[2], level: 1, kind: 'chapter' };
  const level = cmd === 'section' ? 1 : cmd === 'subsection' ? 2 : 3;
  return { title: m[2], level, kind: 'section' };
}

function extractLeadingOptionalArg(text: string): { label: string | null; body: string } {
  const m = text.match(/^\s*\[([^\]]+)\]\s*/);
  if (!m) return { label: null, body: text };
  return { label: m[1].trim(), body: text.slice(m[0].length) };
}

// ─── display math ($$...$$, \[...\]) ─────────────────────────────────────────

/**
 * Split a text chunk by $$...$$ and \[...\] display math delimiters,
 * returning an array of { text, isMath } segments.
 */
function splitDisplayMath(text: string): Array<{ content: string; isMath: boolean }> {
  const segments: Array<{ content: string; isMath: boolean }> = [];
  // Match $$...$$ or \[...\]
  const re = /(\$\$[\s\S]*?\$\$|\\\[[\s\S]*?\\\])/g;
  let last = 0;
  let match: RegExpExecArray | null;
  while ((match = re.exec(text)) !== null) {
    if (match.index > last) {
      segments.push({ content: text.slice(last, match.index), isMath: false });
    }
    segments.push({ content: match[0], isMath: true });
    last = match.index + match[0].length;
  }
  if (last < text.length) {
    segments.push({ content: text.slice(last), isMath: false });
  }
  return segments;
}

// ─── inline math checker ─────────────────────────────────────────────────────

/** Return true if the text contains at least one $...$ (not $$) inline formula. */
function hasInlineMath(text: string): boolean {
  // Match single $ not preceded/followed by another $
  return /(?<!\$)\$(?!\$)[\s\S]*?(?<!\$)\$(?!\$)/.test(text);
}

// ─── balanced-brace extractor ────────────────────────────────────────────────

/** Extract the content of the next balanced {...} starting at `pos`. */
function extractBracedArg(text: string, pos: number): { content: string; end: number } | null {
  if (text[pos] !== '{') return null;
  let depth = 0;
  let i = pos;
  while (i < text.length) {
    if (text[i] === '{') depth++;
    else if (text[i] === '}') {
      depth--;
      if (depth === 0) return { content: text.slice(pos + 1, i), end: i + 1 };
    }
    i++;
  }
  return null;
}

function extractCommandAt(text: string, command: string, startIndex = 0): {
  full: string;
  content: string;
  start: number;
  end: number;
} | null {
  const idx = text.indexOf(command, startIndex);
  if (idx === -1) return null;
  const argStart = idx + command.length;
  const arg = extractBracedArg(text, argStart);
  if (!arg) return null;
  return {
    full: text.slice(idx, arg.end),
    content: arg.content,
    start: idx,
    end: arg.end,
  };
}

function stripAndCollectFancyheads(source: string): {
  left: string | null;
  right: string | null;
  stripped: string;
  latexSource: string;
} {
  let left: string | null = null;
  let right: string | null = null;
  let stripped = '';
  let latexSource = '';
  let cursor = 0;

  while (cursor < source.length) {
    const idx = source.indexOf('\\fancyhead[', cursor);
    if (idx === -1) {
      stripped += source.slice(cursor);
      break;
    }

    stripped += source.slice(cursor, idx);
    const sideStart = idx + '\\fancyhead['.length;
    const sideEnd = source.indexOf(']', sideStart);
    if (sideEnd === -1 || source[sideEnd + 1] !== '{') {
      stripped += source[idx];
      cursor = idx + 1;
      continue;
    }

    const side = source.slice(sideStart, sideEnd).trim().toUpperCase();
    const arg = extractBracedArg(source, sideEnd + 1);
    if (!arg) {
      stripped += source[idx];
      cursor = idx + 1;
      continue;
    }

    const full = source.slice(idx, arg.end);
    latexSource += `${latexSource ? '\n' : ''}${full}`;
    if (side === 'L') left = arg.content.trim();
    if (side === 'R') right = arg.content.trim();
    cursor = arg.end;
  }

  return { left, right, stripped, latexSource };
}

function extractLeadingCue(source: string): { cue: string | null; stripped: string } {
  const found = extractCommandAt(source, '\\cue');
  if (!found) return { cue: null, stripped: source };
  return {
    cue: cleanPlainLatexText(found.content),
    stripped: `${source.slice(0, found.start)}${source.slice(found.end)}`.trim(),
  };
}

function extractSummaryCommand(source: string): { content: string; full: string } | null {
  const trimmed = source.trim();
  const found = extractCommandAt(trimmed, '\\summary');
  if (!found) return null;
  const leftover = `${trimmed.slice(0, found.start)}${trimmed.slice(found.end)}`.trim();
  if (leftover.length > 0) return null;
  return { content: found.content.trim(), full: found.full };
}

/**
 * Replace \MyBox{content} with a ___box___...___endbox___ marker.
 * Uses balanced-brace extraction to handle nested {} inside content.
 */
function preprocessMyBox(text: string): string {
  const cmd = '\\MyBox';
  let result = '';
  let i = 0;
  while (i < text.length) {
    const idx = text.indexOf(cmd, i);
    if (idx === -1) { result += text.slice(i); break; }
    result += text.slice(i, idx);
    const afterCmd = idx + cmd.length;
    const arg = extractBracedArg(text, afterCmd);
    if (!arg) { result += cmd; i = afterCmd; continue; }
    result += `\n___box___${arg.content}___endbox___\n`;
    i = arg.end;
  }
  return result;
}

/**
 * Replace \formulabox{label}{formula} with $$formula$$.
 * Uses balanced-brace extraction to handle nested {} inside the formula.
 */
function preprocessFormulabox(text: string): string {
  const cmd = '\\formulabox';
  let result = '';
  let i = 0;
  while (i < text.length) {
    const idx = text.indexOf(cmd, i);
    if (idx === -1) { result += text.slice(i); break; }
    result += text.slice(i, idx);
    const afterCmd = idx + cmd.length;
    // Extract first arg {label}
    const arg1 = extractBracedArg(text, afterCmd);
    if (!arg1) { result += cmd; i = afterCmd; continue; }
    // Extract second arg {formula}
    const arg2 = extractBracedArg(text, arg1.end);
    if (!arg2) { result += cmd; i = afterCmd; continue; }
    result += `\n$$${arg2.content}$$\n`;
    i = arg2.end;
  }
  return result;
}

// ─── main text-chunk tokenizer ────────────────────────────────────────────────

/**
 * Given a chunk of text (no block-level envs), split it into Blocks:
 *  - section headers
 *  - display math ($$...$$, \[...\])
 *  - paragraphs (with inline math if present)
 */
function tokenizeTextChunk(text: string, blocks: Block[], templateId?: string): void {
  text = stripLatexComments(text);

  // Pre-process custom template commands before tokenizing
  // \sectionbar{title} → \section{title}
  text = text.replace(/\\sectionbar\{([^}]*)\}/g, '\\section{$1}');
  // \cheatsection{title} / \cheatsub{title} for clean_3cols_landscape
  text = text.replace(/\\cheatsection\{([^}]*)\}/g, '\\section{$1}');
  text = text.replace(/\\cheatsub\{([^}]*)\}/g, '\\subsection{$1}');
  if (templateId === 'clean_3cols_landscape') {
    text = preprocessClean3TitleBar(text);
  }
  // \MyBox{content} → ___box___content___endbox___ marker
  text = preprocessMyBox(text);
  // \formulabox{label}{formula} → $$formula$$
  text = preprocessFormulabox(text);
  // \HR → ___hr___ marker (horizontal rule separator)
  text = text.replace(/\\HR\b/g, '\n___hr___\n');

  // First split by section commands
  const parts: Array<{ content: string; isSection: boolean }> = [];
  let last = 0;
  let m: RegExpExecArray | null;
  SECTION_RE.lastIndex = 0;
  while ((m = SECTION_RE.exec(text)) !== null) {
    if (m.index > last) {
      parts.push({ content: text.slice(last, m.index), isSection: false });
    }
    parts.push({ content: m[0], isSection: true });
    last = m.index + m[0].length;
  }
  if (last < text.length) {
    parts.push({ content: text.slice(last), isSection: false });
  }

  for (const part of parts) {
    if (part.isSection) {
      const { title, level, kind } = extractSectionInfo(part.content);
      if (kind === 'chapter') {
        blocks.push({
          id: makeId('chapter'),
          type: 'chapter',
          latex_source: title,
        });
      } else {
        blocks.push({
          id: makeId('section'),
          type: 'section',
          latex_source: title,
          level,
        });
      }
      continue;
    }

    // Split by ___hr___ markers first, then by ___box___ markers, then by display math
    const hrParts = part.content.split('___hr___');
    for (let hIdx = 0; hIdx < hrParts.length; hIdx++) {
      if (hIdx > 0) {
        blocks.push({ id: makeId('hr'), type: 'hr', latex_source: '' });
      }

      // Split by ___box___...___endbox___ markers
      const boxRe = /___box___([\s\S]*?)___endbox___/g;
      let boxLast = 0;
      let boxMatch: RegExpExecArray | null;
      const hrPart = hrParts[hIdx];
      boxRe.lastIndex = 0;
      while ((boxMatch = boxRe.exec(hrPart)) !== null) {
        if (boxMatch.index > boxLast) {
          processTextSegment(hrPart.slice(boxLast, boxMatch.index), blocks, templateId);
        }
        blocks.push({ id: makeId('box'), type: 'box', latex_source: boxMatch[1].trim() });
        boxLast = boxMatch.index + boxMatch[0].length;
      }
      if (boxLast < hrPart.length) {
        processTextSegment(hrPart.slice(boxLast), blocks, templateId);
      }
    }
  }
}

function processTextSegment(text: string, blocks: Block[], templateId?: string): void {
  const mathSegments = splitDisplayMath(text);
  for (const seg of mathSegments) {
    if (seg.isMath) {
      let inner = seg.content;
      if (inner.startsWith('$$')) inner = inner.slice(2, -2);
      else if (inner.startsWith('\\[')) inner = inner.slice(2, -2);
      blocks.push({ id: makeId('formula-block'), type: 'formula-block', latex_source: inner.trim() });
    } else {
      const trimmed = seg.content
        .replace(/\\maketitle/g, '')
        .replace(/\\pagestyle\{[^}]*\}/g, '')
        .replace(/\\pagenumbering\{[^}]*\}/g, '')
        .replace(/\\newpage/g, '')
        .replace(/\\clearpage/g, '')
        .replace(/\\vspace\{[^}]*\}/g, '')
        .replace(/\\HR\b/g, '')
        .replace(/\\\\[ \t]*$/gm, '___newline___')  // convert \\ line-break to marker
        // Remove font-size commands used as standalone lines (e.g. \footnotesize)
        .replace(/^\\(?:footnotesize|scriptsize|small|normalsize|large|Large|LARGE|huge|Huge)\s*$/gm, '')
        .trim();

      if (!trimmed) continue;
      const meaningful = trimmed.replace(/%[^\n]*/g, '').trim();
      if (!meaningful) continue;

      // Strip orphaned braces left after LaTeX command removal (e.g. from title groups)
      const cleaned = trimmed.replace(/^\{([\s\S]*)\}$/, '$1').trim();
      if (!cleaned) continue;

      if (templateId === 'clean_3cols_landscape') {
        const cleanTitleMatch = cleaned.match(
          new RegExp(`^${CLEAN3_TITLE_MARKER}([\\s\\S]*?)${CLEAN3_SUB_MARKER}([\\s\\S]*)$`)
        );
        if (cleanTitleMatch) {
          const title = cleanTitleMatch[1].trim();
          const subtitle = cleanTitleMatch[2].trim();
          blocks.push({
            id: makeId('section'),
            type: 'section',
            latex_source: `${CLEAN3_TITLE_MARKER}${title}${CLEAN3_SUB_MARKER}${subtitle}`,
            level: 1,
          });
          continue;
        }
      }

      // Detect title-like lines: original text used \Large, \huge, \bfseries as document title
      const isTitle = /\\(?:Large|LARGE|huge|Huge|bfseries)/.test(trimmed);
      if (isTitle) {
        // Extract meaningful text: preserve \hfill as a marker so the renderer
        // can keep the left/right title alignment similar to the compiled PDF.
        const titleText = cleaned
          .replace(/\\(?:Large|LARGE|huge|Huge|large|bfseries|mdseries|normalsize|small|scriptsize|footnotesize)\b/g, '')
          .replace(/\\hfill/g, ' ___HFILL___ ')
          .replace(/\\[a-zA-Z]+\*?(?:\{[^}]*\})?/g, '')
          .replace(/[{}]/g, '')
          .replace(/\s+/g, ' ')
          .replace(/\s*___HFILL___\s*/g, ' ___HFILL___ ')
          .trim();
        if (titleText) {
          blocks.push({ id: makeId('section'), type: 'section', latex_source: titleText, level: 1 });
        }
        continue;
      }

      const type: BlockType = hasInlineMath(cleaned) ? 'formula-inline' : 'paragraph';
      blocks.push({ id: makeId(type), type, latex_source: cleaned });
    }
  }
}

// ─── main parser ─────────────────────────────────────────────────────────────

/**
 * Internal parser that does NOT reset _idCounter.
 * Used for recursive calls (e.g. multicols) so IDs remain unique across the document.
 */
function parseLatexInternal(latex: string, templateId?: string): Block[] {
  const blocks: Block[] = [];
  let remaining = stripPreamble(latex);

  // Iteratively find the earliest \begin{env} in remaining text,
  // tokenize the text before it, then handle the env block.
  while (remaining.length > 0) {
    // Find the earliest \begin{...} of any known env
    let earliest: { env: string; start: number } | null = null;

    for (const env of BLOCK_ENVS) {
      const tag = `\\begin{${env}}`;
      const idx = remaining.indexOf(tag);
      if (idx !== -1) {
        if (earliest === null || idx < earliest.start) {
          earliest = { env, start: idx };
        }
      }
    }

    if (earliest === null) {
      // No more known environments — tokenize remaining text
      tokenizeTextChunk(remaining, blocks, templateId);
      break;
    }

    // Tokenize text before this environment
    if (earliest.start > 0) {
      tokenizeTextChunk(remaining.slice(0, earliest.start), blocks, templateId);
    }

    // Extract the environment
    const extracted = extractEnv(remaining, earliest.env, earliest.start);
    if (!extracted) {
      // Malformed: skip the \begin tag and continue
      remaining = remaining.slice(earliest.start + `\\begin{${earliest.env}}`.length);
      continue;
    }

    const env = earliest.env;

    if (MATH_ENVS.has(env)) {
      blocks.push({
        id: makeId('formula-block'),
        type: 'formula-block',
        latex_source: extracted.full,
      });
    } else if (LIST_ENVS.has(env)) {
      blocks.push({
        id: makeId('list'),
        type: 'list',
        latex_source: extracted.full,
      });
    } else if (TABLE_ENVS.has(env)) {
      blocks.push({
        id: makeId('table'),
        type: 'table',
        latex_source: extracted.full,
      });
    } else if (env === 'multicols' || env === 'multicols*') {
      // Strip optional {N} column-count argument and capture column count
      const colMatch = extracted.inner.match(/^\s*\{(\d+)\}/);
      const colCount = colMatch ? colMatch[1] : '2';
      const innerContent = extracted.inner.replace(/^\s*\{[^}]*\}/, '');
      // Emit col-start marker, recurse using internal parser (no counter reset), emit col-end marker
      blocks.push({ id: makeId('col-start'), type: 'col-start', latex_source: colCount });
      const innerBlocks = parseLatexInternal(innerContent, templateId);
      blocks.push(...innerBlocks);
      blocks.push({ id: makeId('col-end'), type: 'col-end', latex_source: '' });
    } else if (
      env === 'definition' ||
      env === 'theorem' ||
      env === 'proposition' ||
      env === 'obs' ||
      env === 'observation' ||
      env === 'example' ||
      env === 'example*' ||
      env === 'lemma' ||
      env === 'corollary' ||
      env === 'remark' ||
      env === 'proof'
    ) {
      const { label, body } = extractLeadingOptionalArg(extracted.inner);
      const subtype: BoxSubtype =
        env === 'obs' ? 'observation' :
        env === 'example*' ? 'example' :
        (env as BoxSubtype);
      blocks.push({
        id: makeId('box'),
        type: 'box',
        latex_source: body.trim(),
        boxSubtype: subtype,
        label: label ?? undefined,
      });
    } else if (env === 'workedexample' || env === 'keypoint' || env === 'warning') {
      const { label, body } = extractLeadingOptionalArg(extracted.inner);
      if (label) {
        blocks.push({
          id: makeId('section'),
          type: 'section',
          latex_source: env === 'workedexample' ? `Example: ${label}` : label,
          level: 2,
        });
      }
      const innerBlocks = parseLatexFragment(body);
      blocks.push(...innerBlocks);
    } else {
      // tcolorbox, workedexample, keypoint, warning, lemma, corollary, remark, proof, etc.
      // Recurse into inner content so math/text blocks are preserved
      const innerBlocks = parseLatexFragment(extracted.inner, templateId);
      blocks.push(...innerBlocks);
    }

    remaining = remaining.slice(extracted.end);
  }

  return blocks.filter(b =>
    b.latex_source.trim().length > 0 || b.type === 'hr' || b.type === 'col-end'
  );
}

/**
 * Annotate blocks with sourceStart/sourceEnd offsets into the original LaTeX string.
 * Offsets are absolute (include preamble) so they can be used directly with fullLatex.
 *
 * Strategy: for each block, find the Nth occurrence of its latex_source in the full
 * source, where N equals the number of preceding blocks with the same latex_source.
 * This is identical to the "robust replace" strategy in LatexViewer (Mejora E).
 *
 * Blocks that cannot be located (e.g. col-start/col-end structural markers, or blocks
 * whose source was transformed during parsing) are left without offsets.
 */
function annotateBlockOffsets(blocks: Block[], fullSource: string): void {
  // Track how many times we've seen each latex_source so far
  const seenCounts = new Map<string, number>();

  for (const block of blocks) {
    // Skip structural markers that don't have literal source matches
    if (block.type === 'col-start' || block.type === 'col-end' || block.type === 'hr') {
      continue;
    }

    const source = block.latex_source;
    if (!source || source.length === 0) continue;

    const occurrenceIndex = seenCounts.get(source) ?? 0;
    seenCounts.set(source, occurrenceIndex + 1);

    // Find the (occurrenceIndex+1)-th occurrence
    let searchFrom = 0;
    let foundIdx = -1;
    for (let n = 0; n <= occurrenceIndex; n++) {
      const idx = fullSource.indexOf(source, searchFrom);
      if (idx === -1) { foundIdx = -1; break; }
      foundIdx = idx;
      searchFrom = idx + 1;
    }

    if (foundIdx !== -1) {
      block.sourceStart = foundIdx;
      block.sourceEnd = foundIdx + source.length;
    }
  }
}

function normalizeCornellBlocks(blocks: Block[]): Block[] {
  const normalized: Block[] = [];
  let pendingCue: string | null = null;

  for (const originalBlock of blocks) {
    let block: Block = { ...originalBlock };

    const fancyheads = stripAndCollectFancyheads(block.latex_source);
    if (fancyheads.left || fancyheads.right) {
      normalized.push({
        id: makeId('page-header'),
        type: 'page-header',
        latex_source: fancyheads.latexSource,
        headerLeft: fancyheads.left ?? undefined,
        headerRight: fancyheads.right ?? undefined,
      });
      block = { ...block, latex_source: fancyheads.stripped.trim() };
      if (!block.latex_source && block.type === 'paragraph') continue;
    }

    const cue = extractLeadingCue(block.latex_source);
    if (cue.cue) {
      pendingCue = cue.cue;
      block = { ...block, latex_source: cue.stripped };
    }

    if (!block.latex_source.trim() && block.type !== 'hr' && block.type !== 'col-end') {
      continue;
    }

    const summary = extractSummaryCommand(block.latex_source);
    if (summary) {
      normalized.push({
        ...block,
        type: 'box',
        boxSubtype: 'summary',
        latex_source: summary.content,
        cue: pendingCue ?? block.cue,
      });
      pendingCue = null;
      continue;
    }

    if (
      pendingCue &&
      block.type !== 'page-header' &&
      block.type !== 'section' &&
      block.type !== 'chapter' &&
      block.type !== 'hr' &&
      block.type !== 'col-start' &&
      block.type !== 'col-end'
    ) {
      block = { ...block, cue: pendingCue };
      pendingCue = null;
    }

    normalized.push(block);
  }

  return normalized;
}

/** Templates that use a report-style cover page + chapter structure in the PDF. */
const REPORT_STYLE_TEMPLATES = new Set(['lecture_notes']);

/**
 * Public entry point: resets the ID counter then delegates to the internal parser.
 * Always call this (not parseLatexInternal) from outside this module.
 */
export function parseLatex(latex: string, options?: ParseOptions): Block[] {
  _idCounter = 0;
  const templateId = options?.templateId;
  const isReportStyle = !!templateId && REPORT_STYLE_TEMPLATES.has(templateId);

  // Strip preamble up-front so cover extraction only considers the document body.
  const body = stripPreamble(latex);

  // Extract \title / \author / \date / \maketitle / titlepage from the body
  const meta = extractCoverMetadata(body);

  // Decide whether to emit a cover block. We emit when metadata is present AND
  // either \maketitle / \begin{titlepage} was seen (any template) or the template
  // is report-style (always emits a cover, like the compiled PDF).
  const shouldEmitCover =
    (meta.title || meta.author || meta.date) && (meta.hadMakeTitle || isReportStyle);

  // For report-style templates, promote top-level \section{...} to \chapter{...}
  // so the Interactive view mirrors the PDF's chapter numbering.
  let sourceForParse = stripLatexComments(meta.stripped);
  if (isReportStyle) {
    sourceForParse = promoteTopLevelSectionsToChapters(sourceForParse);
  }

  const coverBlocks: Block[] = [];
  if (shouldEmitCover) {
    coverBlocks.push({
      id: makeId('cover'),
      type: 'cover',
      latex_source: '',
      title: meta.title ?? undefined,
      author: meta.author ?? undefined,
      date: meta.date ?? undefined,
    });
  }

  let bodyBlocks = parseLatexInternal(sourceForParse, templateId);
  if (templateId === 'cornell') {
    bodyBlocks = normalizeCornellBlocks(bodyBlocks);
  }

  // Auto-assign sequential chapter numbers for `chapter` blocks so the renderer
  // can display "Chapter N" prefixes identical to the PDF output.
  let chapterCounter = 0;
  for (const block of bodyBlocks) {
    if (block.type === 'chapter') {
      chapterCounter += 1;
      block.chapterNumber = chapterCounter;
    }
  }

  const blocks = [...coverBlocks, ...bodyBlocks];
  // IA-M1: annotate blocks with absolute offsets into the original source
  annotateBlockOffsets(blocks, latex);
  return blocks;
}

/**
 * Promote top-level `\section{...}` occurrences (not subsection/subsubsection) to
 * `\chapter{...}`. Used for report-style templates so the Interactive viewer
 * mirrors the PDF, which compiles these notes with the `report` class + `\chapter`.
 * Only the command name is rewritten — content is left untouched.
 */
function promoteTopLevelSectionsToChapters(text: string): string {
  return text.replace(/\\section(\*?)\{/g, '\\chapter$1{');
}

// ─── IA-M2: block-level template stubs ──────────────────────────────────────

export type NewBlockType = 'paragraph' | 'formula' | 'list' | 'section';

/** Generate placeholder LaTeX source for a newly inserted block. */
export function newBlockLatex(type: NewBlockType): string {
  switch (type) {
    case 'paragraph':
      return 'New paragraph text here.';
    case 'formula':
      return '\\[\nf(x) = \\int_{a}^{b} g(t)\\, dt\n\\]';
    case 'list':
      return '\\begin{itemize}\n  \\item First item\n  \\item Second item\n\\end{itemize}';
    case 'section':
      return '\\section{New Section}';
  }
}

/**
 * Reconstruct the full LaTeX source from a Block[] array.
 * Preserves the original preamble (\documentclass … \begin{document}) and
 * \end{document} tail. Only the document body (between \begin{document} and
 * \end{document}) is rebuilt from the blocks.
 *
 * col-start blocks are unwrapped (their multicols wrapper is re-emitted around
 * the consecutive non-col-end blocks). col-end blocks mark the end of the region.
 * All other blocks are emitted as their latex_source separated by blank lines.
 */
export function reconstructLatexFromBlocks(blocks: Block[], originalSource: string): string {
  const restoreParserMarkers = (source: string): string =>
    source
      .replace(/___HFILL___/g, '\\hfill')
      .replace(/___newline___/g, '\\\\');
  const cueLine = (block: Block): string | null =>
    block.cue?.trim() ? `\\cue{${block.cue.trim()}}` : null;

  // Extract preamble up to and including \begin{document}
  const beginDocTag = '\\begin{document}';
  const endDocTag = '\\end{document}';
  const beginIdx = originalSource.indexOf(beginDocTag);
  const preamble = beginIdx !== -1
    ? originalSource.slice(0, beginIdx + beginDocTag.length)
    : '';

  // Reconstruct body
  const lines: string[] = [];
  let i = 0;

  while (i < blocks.length) {
    const block = blocks[i];

    if (block.type === 'col-start') {
      // The col-start block's latex_source is the column count as a string (from parser).
      // We re-wrap the enclosed blocks in \begin{multicols}{N}...\end{multicols}.
      const colCount = parseInt(block.latex_source) || 2;
      lines.push(`\\begin{multicols}{${colCount}}`);
      i++;
      while (i < blocks.length && blocks[i].type !== 'col-end') {
        const inner = blocks[i];
        const cue = cueLine(inner);
        if (cue) lines.push(cue);
        if (inner.latex_source.trim()) {
          lines.push(restoreParserMarkers(inner.latex_source));
        }
        i++;
      }
      lines.push('\\end{multicols}');
      i++; // skip col-end
    } else if (block.type === 'col-end' || block.type === 'hr') {
      // hr → emit the rule; col-end is handled above
      if (block.type === 'hr') lines.push('\\hrule');
      i++;
    } else if (block.type === 'cover') {
      // Re-emit the \title / \author / \date / \maketitle block so the compiled
      // PDF still renders a cover page even after round-tripping through the viewer.
      if (block.title) lines.push(`\\title{${block.title}}`);
      if (block.author) lines.push(`\\author{${block.author}}`);
      if (block.date) lines.push(`\\date{${block.date}}`);
      if (block.title || block.author || block.date) lines.push('\\maketitle');
      i++;
    } else if (block.type === 'page-header') {
      if (block.latex_source.trim()) {
        lines.push(restoreParserMarkers(block.latex_source));
      }
      i++;
    } else if (block.type === 'chapter') {
      lines.push(`\\chapter{${block.latex_source}}`);
      i++;
    } else if (block.type === 'box' && block.boxSubtype === 'summary') {
      const cue = cueLine(block);
      if (cue) lines.push(cue);
      lines.push(`\\summary{${restoreParserMarkers(block.latex_source)}}`);
      i++;
    } else if (block.type === 'box' && block.boxSubtype) {
      const env = block.boxSubtype;
      const labelPart = block.label ? `[${block.label}]` : '';
      const cue = cueLine(block);
      if (cue) lines.push(cue);
      lines.push(`\\begin{${env}}${labelPart}`);
      if (block.latex_source.trim()) {
        lines.push(restoreParserMarkers(block.latex_source));
      }
      lines.push(`\\end{${env}}`);
      i++;
    } else {
      if (block.latex_source.trim()) {
        const cue = cueLine(block);
        if (cue) lines.push(cue);
        lines.push(restoreParserMarkers(block.latex_source));
      }
      i++;
    }
  }

  const body = lines.join('\n\n');

  if (preamble) {
    return `${preamble}\n${body}\n${endDocTag}`;
  }
  // No preamble found — return body as-is (fallback for bare LaTeX fragments)
  return body;
}

/**
 * Parse a fragment (inner content of an env) without stripping preamble.
 * Used for theorem-like and tcolorbox environments.
 */
function parseLatexFragment(fragment: string, templateId?: string): Block[] {
  return parseLatexInternal(fragment, templateId).filter(b =>
    b.latex_source.trim().length > 0 || b.type === 'hr' || b.type === 'col-end'
  );
}
