/**
 * latex-parser.ts
 * Manual (regex + split) parser for LaTeX source generated by BetterNotes templates.
 * No external parsing libraries — intentionally lightweight for F3-M1 PoC.
 *
 * Supported block types:
 *   section        — \section{}, \section*{}, \subsection{}, \subsection*{}, \subsubsection{}
 *   formula-block  — $$...$$, \[...\], \begin{equation}..., \begin{align*}..., etc.
 *   formula-inline — $...$ within paragraph text
 *   table          — \begin{tabular}...\end{tabular}
 *   list           — \begin{itemize}...\end{itemize}, \begin{enumerate}...\end{enumerate}
 *   paragraph      — everything else (plain text with possible inline math)
 */

export type BlockType =
  | 'section'
  | 'formula-block'
  | 'formula-inline'
  | 'table'
  | 'list'
  | 'paragraph'
  | 'hr'
  | 'box'
  | 'col-start'
  | 'col-end';

export interface Block {
  id: string;
  type: BlockType;
  latex_source: string;
  /** section level: 1 = \section, 2 = \subsection, 3 = \subsubsection */
  level?: number;
  /** For type === 'box': the theorem-like environment that produced this block */
  boxSubtype?: 'definition' | 'theorem' | 'proposition' | 'observation' | 'example';
  /** Character offset in the original source where this block starts (after preamble strip) */
  sourceStart?: number;
  /** Character offset in the original source where this block ends (exclusive) */
  sourceEnd?: number;
}

// ─── helpers ─────────────────────────────────────────────────────────────────

let _idCounter = 0;
function makeId(prefix: string): string {
  return `${prefix}-${++_idCounter}`;
}

/**
 * Extract the balanced content inside \begin{env}...\end{env}.
 * Returns [fullMatch, innerContent] or null.
 */
function extractEnv(
  source: string,
  env: string,
  startIndex = 0
): { full: string; inner: string; start: number; end: number } | null {
  const openTag = `\\begin{${env}}`;
  const closeTag = `\\end{${env}}`;
  const start = source.indexOf(openTag, startIndex);
  if (start === -1) return null;
  const end = source.indexOf(closeTag, start + openTag.length);
  if (end === -1) return null;
  return {
    full: source.slice(start, end + closeTag.length),
    inner: source.slice(start + openTag.length, end),
    start,
    end: end + closeTag.length,
  };
}

// ─── strip LaTeX preamble/document wrapper ────────────────────────────────────

/**
 * Remove everything before \begin{document} and after \end{document},
 * and also strip the \begin{document} / \end{document} tags themselves.
 * If no \begin{document} found, return the whole source as-is.
 */
function stripPreamble(source: string): string {
  const beginDoc = source.indexOf('\\begin{document}');
  const endDoc = source.indexOf('\\end{document}');
  if (beginDoc === -1) return source;
  const inner = source.slice(beginDoc + '\\begin{document}'.length, endDoc === -1 ? undefined : endDoc);
  return inner;
}

// ─── block-level environment extraction ──────────────────────────────────────

const BLOCK_ENVS = [
  // math environments
  'equation', 'equation*', 'align', 'align*', 'alignat', 'alignat*',
  'gather', 'gather*', 'multline', 'multline*', 'flalign', 'flalign*',
  'eqnarray', 'eqnarray*',
  // table
  'tabular', 'tabular*', 'tabularx', 'longtable', 'array',
  // list
  'itemize', 'enumerate', 'description',
  // theorem-like (from templates)
  'definition', 'theorem', 'lemma', 'proposition', 'corollary', 'remark',
  'proof', 'obs', 'observation', 'example', 'example*', 'exercise*',
  // tcolorbox environments (lecture_notes template)
  'workedexample', 'keypoint', 'warning',
  // multicol (study_form, 2cols_portrait, landscape_3col_maths)
  'multicols', 'multicols*',
  // other common
  'figure', 'table', 'minipage', 'abstract', 'verbatim',
] as const;

const MATH_ENVS = new Set([
  'equation', 'equation*', 'align', 'align*', 'alignat', 'alignat*',
  'gather', 'gather*', 'multline', 'multline*', 'flalign', 'flalign*',
  'eqnarray', 'eqnarray*',
]);

const LIST_ENVS = new Set(['itemize', 'enumerate', 'description']);

const TABLE_ENVS = new Set(['tabular', 'tabular*', 'tabularx', 'longtable', 'array']);

// ─── section extractor ────────────────────────────────────────────────────────

const SECTION_RE = /\\(subsubsection|subsection|section)\*?\{([^}]*)\}/g;

function extractSectionTitle(raw: string): { title: string; level: number } {
  const m = /\\(subsubsection|subsection|section)\*?\{([^}]*)\}/.exec(raw);
  if (!m) return { title: raw, level: 1 };
  const level = m[1] === 'section' ? 1 : m[1] === 'subsection' ? 2 : 3;
  return { title: m[2], level };
}

// ─── display math ($$...$$, \[...\]) ─────────────────────────────────────────

/**
 * Split a text chunk by $$...$$ and \[...\] display math delimiters,
 * returning an array of { text, isMath } segments.
 */
function splitDisplayMath(text: string): Array<{ content: string; isMath: boolean }> {
  const segments: Array<{ content: string; isMath: boolean }> = [];
  // Match $$...$$ or \[...\]
  const re = /(\$\$[\s\S]*?\$\$|\\\[[\s\S]*?\\\])/g;
  let last = 0;
  let match: RegExpExecArray | null;
  while ((match = re.exec(text)) !== null) {
    if (match.index > last) {
      segments.push({ content: text.slice(last, match.index), isMath: false });
    }
    segments.push({ content: match[0], isMath: true });
    last = match.index + match[0].length;
  }
  if (last < text.length) {
    segments.push({ content: text.slice(last), isMath: false });
  }
  return segments;
}

// ─── inline math checker ─────────────────────────────────────────────────────

/** Return true if the text contains at least one $...$ (not $$) inline formula. */
function hasInlineMath(text: string): boolean {
  // Match single $ not preceded/followed by another $
  return /(?<!\$)\$(?!\$)[\s\S]*?(?<!\$)\$(?!\$)/.test(text);
}

// ─── balanced-brace extractor ────────────────────────────────────────────────

/** Extract the content of the next balanced {...} starting at `pos`. */
function extractBracedArg(text: string, pos: number): { content: string; end: number } | null {
  if (text[pos] !== '{') return null;
  let depth = 0;
  let i = pos;
  while (i < text.length) {
    if (text[i] === '{') depth++;
    else if (text[i] === '}') {
      depth--;
      if (depth === 0) return { content: text.slice(pos + 1, i), end: i + 1 };
    }
    i++;
  }
  return null;
}

/**
 * Replace \MyBox{content} with a ___box___...___endbox___ marker.
 * Uses balanced-brace extraction to handle nested {} inside content.
 */
function preprocessMyBox(text: string): string {
  const cmd = '\\MyBox';
  let result = '';
  let i = 0;
  while (i < text.length) {
    const idx = text.indexOf(cmd, i);
    if (idx === -1) { result += text.slice(i); break; }
    result += text.slice(i, idx);
    const afterCmd = idx + cmd.length;
    const arg = extractBracedArg(text, afterCmd);
    if (!arg) { result += cmd; i = afterCmd; continue; }
    result += `\n___box___${arg.content}___endbox___\n`;
    i = arg.end;
  }
  return result;
}

/**
 * Replace \formulabox{label}{formula} with $$formula$$.
 * Uses balanced-brace extraction to handle nested {} inside the formula.
 */
function preprocessFormulabox(text: string): string {
  const cmd = '\\formulabox';
  let result = '';
  let i = 0;
  while (i < text.length) {
    const idx = text.indexOf(cmd, i);
    if (idx === -1) { result += text.slice(i); break; }
    result += text.slice(i, idx);
    const afterCmd = idx + cmd.length;
    // Extract first arg {label}
    const arg1 = extractBracedArg(text, afterCmd);
    if (!arg1) { result += cmd; i = afterCmd; continue; }
    // Extract second arg {formula}
    const arg2 = extractBracedArg(text, arg1.end);
    if (!arg2) { result += cmd; i = afterCmd; continue; }
    result += `\n$$${arg2.content}$$\n`;
    i = arg2.end;
  }
  return result;
}

// ─── main text-chunk tokenizer ────────────────────────────────────────────────

/**
 * Given a chunk of text (no block-level envs), split it into Blocks:
 *  - section headers
 *  - display math ($$...$$, \[...\])
 *  - paragraphs (with inline math if present)
 */
function tokenizeTextChunk(text: string, blocks: Block[]): void {
  // Pre-process custom template commands before tokenizing
  // \sectionbar{title} → \section{title}
  text = text.replace(/\\sectionbar\{([^}]*)\}/g, '\\section{$1}');
  // \MyBox{content} → ___box___content___endbox___ marker
  text = preprocessMyBox(text);
  // \formulabox{label}{formula} → $$formula$$
  text = preprocessFormulabox(text);
  // \HR → ___hr___ marker (horizontal rule separator)
  text = text.replace(/\\HR\b/g, '\n___hr___\n');

  // First split by section commands
  const parts: Array<{ content: string; isSection: boolean }> = [];
  let last = 0;
  let m: RegExpExecArray | null;
  SECTION_RE.lastIndex = 0;
  while ((m = SECTION_RE.exec(text)) !== null) {
    if (m.index > last) {
      parts.push({ content: text.slice(last, m.index), isSection: false });
    }
    parts.push({ content: m[0], isSection: true });
    last = m.index + m[0].length;
  }
  if (last < text.length) {
    parts.push({ content: text.slice(last), isSection: false });
  }

  for (const part of parts) {
    if (part.isSection) {
      const { title, level } = extractSectionTitle(part.content);
      blocks.push({
        id: makeId('section'),
        type: 'section',
        latex_source: title,
        level,
      });
      continue;
    }

    // Split by ___hr___ markers first, then by ___box___ markers, then by display math
    const hrParts = part.content.split('___hr___');
    for (let hIdx = 0; hIdx < hrParts.length; hIdx++) {
      if (hIdx > 0) {
        blocks.push({ id: makeId('hr'), type: 'hr', latex_source: '' });
      }

      // Split by ___box___...___endbox___ markers
      const boxRe = /___box___([\s\S]*?)___endbox___/g;
      let boxLast = 0;
      let boxMatch: RegExpExecArray | null;
      const hrPart = hrParts[hIdx];
      boxRe.lastIndex = 0;
      while ((boxMatch = boxRe.exec(hrPart)) !== null) {
        if (boxMatch.index > boxLast) {
          processTextSegment(hrPart.slice(boxLast, boxMatch.index), blocks);
        }
        blocks.push({ id: makeId('box'), type: 'box', latex_source: boxMatch[1].trim() });
        boxLast = boxMatch.index + boxMatch[0].length;
      }
      if (boxLast < hrPart.length) {
        processTextSegment(hrPart.slice(boxLast), blocks);
      }
    }
  }
}

function processTextSegment(text: string, blocks: Block[]): void {
  const mathSegments = splitDisplayMath(text);
  for (const seg of mathSegments) {
    if (seg.isMath) {
      let inner = seg.content;
      if (inner.startsWith('$$')) inner = inner.slice(2, -2);
      else if (inner.startsWith('\\[')) inner = inner.slice(2, -2);
      blocks.push({ id: makeId('formula-block'), type: 'formula-block', latex_source: inner.trim() });
    } else {
      const trimmed = seg.content
        .replace(/\\maketitle/g, '')
        .replace(/\\pagestyle\{[^}]*\}/g, '')
        .replace(/\\pagenumbering\{[^}]*\}/g, '')
        .replace(/\\newpage/g, '')
        .replace(/\\clearpage/g, '')
        .replace(/\\vspace\{[^}]*\}/g, '')
        .replace(/\\hfill/g, ' ')
        .replace(/\\HR\b/g, '')
        .replace(/\\\\[ \t]*$/gm, '___newline___')  // convert \\ line-break to marker
        // Remove font-size commands used as standalone lines (e.g. \footnotesize)
        .replace(/^\\(?:footnotesize|scriptsize|small|normalsize|large|Large|LARGE|huge|Huge)\s*$/gm, '')
        .trim();

      if (!trimmed) continue;
      const meaningful = trimmed.replace(/%[^\n]*/g, '').trim();
      if (!meaningful) continue;

      // Strip orphaned braces left after LaTeX command removal (e.g. from title groups)
      const cleaned = trimmed.replace(/^\{([\s\S]*)\}$/, '$1').trim();
      if (!cleaned) continue;

      // Detect title-like lines: original text used \Large, \huge, \bfseries as document title
      const isTitle = /\\(?:Large|LARGE|huge|Huge|bfseries)/.test(trimmed);
      if (isTitle) {
        // Extract meaningful text: strip all LaTeX commands, keep text and \hfill→space
        const titleText = cleaned
          .replace(/\\(?:Large|LARGE|huge|Huge|large|bfseries|mdseries|normalsize|small|scriptsize|footnotesize)\b/g, '')
          .replace(/\\hfill/g, ' — ')
          .replace(/\\[a-zA-Z]+\*?(?:\{[^}]*\})?/g, '')
          .replace(/[{}]/g, '')
          .replace(/\s+/g, ' ')
          .trim();
        if (titleText) {
          blocks.push({ id: makeId('section'), type: 'section', latex_source: titleText, level: 1 });
        }
        continue;
      }

      const type: BlockType = hasInlineMath(cleaned) ? 'formula-inline' : 'paragraph';
      blocks.push({ id: makeId(type), type, latex_source: cleaned });
    }
  }
}

// ─── main parser ─────────────────────────────────────────────────────────────

/**
 * Internal parser that does NOT reset _idCounter.
 * Used for recursive calls (e.g. multicols) so IDs remain unique across the document.
 */
function parseLatexInternal(latex: string): Block[] {
  const blocks: Block[] = [];
  let remaining = stripPreamble(latex);

  // Iteratively find the earliest \begin{env} in remaining text,
  // tokenize the text before it, then handle the env block.
  while (remaining.length > 0) {
    // Find the earliest \begin{...} of any known env
    let earliest: { env: string; start: number } | null = null;

    for (const env of BLOCK_ENVS) {
      const tag = `\\begin{${env}}`;
      const idx = remaining.indexOf(tag);
      if (idx !== -1) {
        if (earliest === null || idx < earliest.start) {
          earliest = { env, start: idx };
        }
      }
    }

    if (earliest === null) {
      // No more known environments — tokenize remaining text
      tokenizeTextChunk(remaining, blocks);
      break;
    }

    // Tokenize text before this environment
    if (earliest.start > 0) {
      tokenizeTextChunk(remaining.slice(0, earliest.start), blocks);
    }

    // Extract the environment
    const extracted = extractEnv(remaining, earliest.env, earliest.start);
    if (!extracted) {
      // Malformed: skip the \begin tag and continue
      remaining = remaining.slice(earliest.start + `\\begin{${earliest.env}}`.length);
      continue;
    }

    const env = earliest.env;

    if (MATH_ENVS.has(env)) {
      blocks.push({
        id: makeId('formula-block'),
        type: 'formula-block',
        latex_source: extracted.full,
      });
    } else if (LIST_ENVS.has(env)) {
      blocks.push({
        id: makeId('list'),
        type: 'list',
        latex_source: extracted.full,
      });
    } else if (TABLE_ENVS.has(env)) {
      blocks.push({
        id: makeId('table'),
        type: 'table',
        latex_source: extracted.full,
      });
    } else if (env === 'multicols' || env === 'multicols*') {
      // Strip optional {N} column-count argument and capture column count
      const colMatch = extracted.inner.match(/^\s*\{(\d+)\}/);
      const colCount = colMatch ? colMatch[1] : '2';
      const innerContent = extracted.inner.replace(/^\s*\{[^}]*\}/, '');
      // Emit col-start marker, recurse using internal parser (no counter reset), emit col-end marker
      blocks.push({ id: makeId('col-start'), type: 'col-start', latex_source: colCount });
      const innerBlocks = parseLatexInternal(innerContent);
      blocks.push(...innerBlocks);
      blocks.push({ id: makeId('col-end'), type: 'col-end', latex_source: '' });
    } else if (env === 'definition') {
      blocks.push({ id: makeId('box'), type: 'box', latex_source: extracted.inner.trim(), boxSubtype: 'definition' });
    } else if (env === 'theorem') {
      blocks.push({ id: makeId('box'), type: 'box', latex_source: extracted.inner.trim(), boxSubtype: 'theorem' });
    } else if (env === 'proposition') {
      blocks.push({ id: makeId('box'), type: 'box', latex_source: extracted.inner.trim(), boxSubtype: 'proposition' });
    } else if (env === 'obs' || env === 'observation') {
      blocks.push({ id: makeId('box'), type: 'box', latex_source: extracted.inner.trim(), boxSubtype: 'observation' });
    } else if (env === 'example' || env === 'example*') {
      blocks.push({ id: makeId('box'), type: 'box', latex_source: extracted.inner.trim(), boxSubtype: 'example' });
    } else {
      // tcolorbox, workedexample, keypoint, warning, lemma, corollary, remark, proof, etc.
      // Recurse into inner content so math/text blocks are preserved
      const innerBlocks = parseLatexFragment(extracted.inner);
      blocks.push(...innerBlocks);
    }

    remaining = remaining.slice(extracted.end);
  }

  return blocks.filter(b =>
    b.latex_source.trim().length > 0 || b.type === 'hr' || b.type === 'col-end'
  );
}

/**
 * Annotate blocks with sourceStart/sourceEnd offsets into the original LaTeX string.
 * Offsets are absolute (include preamble) so they can be used directly with fullLatex.
 *
 * Strategy: for each block, find the Nth occurrence of its latex_source in the full
 * source, where N equals the number of preceding blocks with the same latex_source.
 * This is identical to the "robust replace" strategy in LatexViewer (Mejora E).
 *
 * Blocks that cannot be located (e.g. col-start/col-end structural markers, or blocks
 * whose source was transformed during parsing) are left without offsets.
 */
function annotateBlockOffsets(blocks: Block[], fullSource: string): void {
  // Track how many times we've seen each latex_source so far
  const seenCounts = new Map<string, number>();

  for (const block of blocks) {
    // Skip structural markers that don't have literal source matches
    if (block.type === 'col-start' || block.type === 'col-end' || block.type === 'hr') {
      continue;
    }

    const source = block.latex_source;
    if (!source || source.length === 0) continue;

    const occurrenceIndex = seenCounts.get(source) ?? 0;
    seenCounts.set(source, occurrenceIndex + 1);

    // Find the (occurrenceIndex+1)-th occurrence
    let searchFrom = 0;
    let foundIdx = -1;
    for (let n = 0; n <= occurrenceIndex; n++) {
      const idx = fullSource.indexOf(source, searchFrom);
      if (idx === -1) { foundIdx = -1; break; }
      foundIdx = idx;
      searchFrom = idx + 1;
    }

    if (foundIdx !== -1) {
      block.sourceStart = foundIdx;
      block.sourceEnd = foundIdx + source.length;
    }
  }
}

/**
 * Public entry point: resets the ID counter then delegates to the internal parser.
 * Always call this (not parseLatexInternal) from outside this module.
 */
export function parseLatex(latex: string): Block[] {
  _idCounter = 0;
  const blocks = parseLatexInternal(latex);
  // IA-M1: annotate blocks with absolute offsets into the original source
  annotateBlockOffsets(blocks, latex);
  return blocks;
}

// ─── IA-M2: block-level template stubs ──────────────────────────────────────

export type NewBlockType = 'paragraph' | 'formula' | 'list' | 'section';

/** Generate placeholder LaTeX source for a newly inserted block. */
export function newBlockLatex(type: NewBlockType): string {
  switch (type) {
    case 'paragraph':
      return 'New paragraph text here.';
    case 'formula':
      return '\\[\nf(x) = \\int_{a}^{b} g(t)\\, dt\n\\]';
    case 'list':
      return '\\begin{itemize}\n  \\item First item\n  \\item Second item\n\\end{itemize}';
    case 'section':
      return '\\section{New Section}';
  }
}

/**
 * Reconstruct the full LaTeX source from a Block[] array.
 * Preserves the original preamble (\documentclass … \begin{document}) and
 * \end{document} tail. Only the document body (between \begin{document} and
 * \end{document}) is rebuilt from the blocks.
 *
 * col-start blocks are unwrapped (their multicols wrapper is re-emitted around
 * the consecutive non-col-end blocks). col-end blocks mark the end of the region.
 * All other blocks are emitted as their latex_source separated by blank lines.
 */
export function reconstructLatexFromBlocks(blocks: Block[], originalSource: string): string {
  // Extract preamble up to and including \begin{document}
  const beginDocTag = '\\begin{document}';
  const endDocTag = '\\end{document}';
  const beginIdx = originalSource.indexOf(beginDocTag);
  const preamble = beginIdx !== -1
    ? originalSource.slice(0, beginIdx + beginDocTag.length)
    : '';

  // Reconstruct body
  const lines: string[] = [];
  let i = 0;

  while (i < blocks.length) {
    const block = blocks[i];

    if (block.type === 'col-start') {
      // The col-start block's latex_source is the column count as a string (from parser).
      // We re-wrap the enclosed blocks in \begin{multicols}{N}...\end{multicols}.
      const colCount = parseInt(block.latex_source) || 2;
      lines.push(`\\begin{multicols}{${colCount}}`);
      i++;
      while (i < blocks.length && blocks[i].type !== 'col-end') {
        const inner = blocks[i];
        if (inner.latex_source.trim()) {
          lines.push(inner.latex_source);
        }
        i++;
      }
      lines.push('\\end{multicols}');
      i++; // skip col-end
    } else if (block.type === 'col-end' || block.type === 'hr') {
      // hr → emit the rule; col-end is handled above
      if (block.type === 'hr') lines.push('\\hrule');
      i++;
    } else {
      if (block.latex_source.trim()) {
        lines.push(block.latex_source);
      }
      i++;
    }
  }

  const body = lines.join('\n\n');

  if (preamble) {
    return `${preamble}\n${body}\n${endDocTag}`;
  }
  // No preamble found — return body as-is (fallback for bare LaTeX fragments)
  return body;
}

/**
 * Parse a fragment (inner content of an env) without stripping preamble.
 * Used for theorem-like and tcolorbox environments.
 */
function parseLatexFragment(fragment: string): Block[] {
  const blocks: Block[] = [];
  tokenizeTextChunk(fragment, blocks);
  return blocks.filter(b =>
    b.latex_source.trim().length > 0 || b.type === 'hr' || b.type === 'col-end'
  );
}
