-- ============================================================
-- BetterNotes v2 — Migration 4: Seed Templates
-- Proyecto: BetterNotesAI-3 (unnaedblaufyganyconl)
-- ============================================================

INSERT INTO public.templates (id, display_name, description, is_pro, preamble, style_guide, structure_template, structure_example, sort_order)
VALUES

-- ─── landscape_3col_maths ───────────────────────────────────
(
  'landscape_3col_maths',
  '3-Column Landscape (Maths)',
  'A4 landscape with 3 columns — ideal for dense math reference sheets and formula summaries.',
  false,
  E'\\documentclass[10pt]{article}\n\\usepackage[english]{babel}\n\\usepackage[utf8]{inputenc}\n\\usepackage[T1]{fontenc}\n\\usepackage{enumitem}\n\\usepackage{booktabs}\n\\usepackage{amsmath,amsthm,empheq,amssymb,amsfonts,mathrsfs}\n\\usepackage{lmodern}\n\\usepackage{xcolor}\n\\usepackage{geometry}\n\\geometry{a4paper,landscape,left=5mm,right=5mm,top=5mm,bottom=5mm}\n\\usepackage{multicol}\n\\setlength{\\columnseprule}{0.5pt}\n\\setlength{\\columnsep}{0.5cm}\n\\usepackage{titlesec}\n\\titlespacing{\\section}{0pt}{2pt}{0pt}\n\\titlespacing{\\subsection}{0pt}{2pt}{0pt}\n\\titlespacing{\\subsubsection}{0pt}{2pt}{0pt}\n\\titleformat*{\\section}{\\large\\bfseries}\n\\titleformat*{\\subsection}{\\bfseries}\n\\setlength{\\parindent}{0pt}\n\\pagenumbering{gobble}\n\\renewcommand{\\baselinestretch}{1.2}\n\\linespread{0.925}\n\\setlist[itemize]{noitemsep,topsep=0pt,leftmargin=*}\n\\setlist[enumerate]{noitemsep,topsep=0pt,leftmargin=*}\n\\definecolor{green2}{RGB}{61,176,0}\n\\newtheoremstyle{normal}{0pt}{0pt}{\\upshape}{}{\\bfseries}{}{ }{}\n\\theoremstyle{normal}\n\\newtheorem*{definition}{\\textcolor{green2}{Def.}}\n\\newtheorem*{proposition}{\\textcolor{blue}{Prop.}}\n\\newtheorem*{theorem}{\\textcolor{red}{Thm.}}\n\\newtheorem*{obs}{\\textcolor{cyan}{Obs.}}\n\\newtheorem*{example*}{Example}\n\\newtheorem*{exercise*}{Exercise}\n\\newcommand{\\dd}{\\mathrm{d}}\n\\newcommand{\\real}{\\mathbb{R}}\n\\newcommand{\\cplex}{\\mathbb{C}}',
  E'You are generating a 3-COLUMN LANDSCAPE A4 math formula/summary sheet.\n\nLAYOUT RULES:\n- Wrap ALL content in \\begin{multicols*}{3} ... \\end{multicols*}\n- Use \\section*{Topic Name} for major sections\n- Use \\subsection*{Subtopic} for subsections\n- No page numbers (pagenumbering{gobble} is set)\n- Very compact: minimal vertical space, no blank lines between items\n\nCONTENT RULES:\n- Use the theorem environments defined in the preamble: definition, proposition, theorem, obs, example*, exercise*\n- DO NOT redefine these environments\n- Use amsmath for equations: align*, equation*, etc.\n- Keep each entry brief — this is a reference sheet, not an explanation\n- Pack as much useful content as possible\n- End with: \\begin{flushright}\\footnotesize \\textit{made with BetterNotes-AI}\\end{flushright}',
  E'\\begin{document}\n\\begin{multicols*}{3}\n\n% FILL: First major section header using \\section*{Topic Name}\n% FILL: 3-5 key definitions, theorems, or formulas for this section using the theorem environments (definition, theorem, proposition, obs)\n% FILL: Use \\begin{itemize} for lists of formulas or properties\n\n% FILL: Second major section header using \\section*{Topic Name}\n% FILL: Key theorems and results with brief proofs or statements\n% FILL: Display math with align* or equation* for important equations\n\n% FILL: Third major section (and more as needed, filling all 3 columns)\n% FILL: Use \\subsection*{Subtopic} to break large sections\n% FILL: Include worked example using example* environment if helpful\n\n% FILL: Continue with 3-6 more sections covering the requested topic thoroughly\n% FILL: Pack content densely — every line should convey information\n\n\\end{multicols*}\n\\begin{flushright}\\footnotesize \\textit{made with BetterNotes-AI}\\end{flushright}\n\\end{document}',
  E'\\begin{document}\n\\begin{multicols*}{3}\n\n\\section*{Derivatives}\n\n\\begin{definition}\n$f''(x) = \\lim_{h\\to 0}\\frac{f(x+h)-f(x)}{h}$\n\\end{definition}\n\n\\begin{theorem}[Chain Rule]\n$(f\\circ g)''(x) = f''(g(x))\\cdot g''(x)$\n\\end{theorem}\n\n\\begin{obs}\nProduct rule: $(fg)'' = f''g + fg''$\n\\end{obs}\n\n\\subsection*{Common Derivatives}\n\\begin{itemize}\n  \\item $(x^n)'' = nx^{n-1}$\n  \\item $(\\sin x)'' = \\cos x$\n  \\item $(e^x)'' = e^x$\n\\end{itemize}\n\n\\end{multicols*}\n\\begin{flushright}\\footnotesize \\textit{made with BetterNotes-AI}\\end{flushright}\n\\end{document}',
  1
),

-- ─── 2cols_portrait ─────────────────────────────────────────
(
  '2cols_portrait',
  '2-Column Cheat Sheet',
  'A4 portrait with 2 columns — perfect for compact cheat sheets with formulas, definitions, and key results.',
  false,
  E'\\documentclass[10pt]{article}\n\\usepackage[margin=0.45in]{geometry}\n\\usepackage{amsmath,amssymb}\n\\usepackage{lmodern}\n\\usepackage{microtype}\n\\usepackage{multicol}\n\\usepackage{enumitem}\n\\setlength{\\parindent}{0pt}\n\\setlength{\\parskip}{0.15em}\n\\setlength{\\columnsep}{0.35cm}\n\\setlength{\\abovedisplayskip}{0.25em}\n\\setlength{\\belowdisplayskip}{0.25em}\n\\setlength{\\abovedisplayshortskip}{0.15em}\n\\setlength{\\belowdisplayshortskip}{0.15em}\n\\setlist[itemize]{leftmargin=1.1em,itemsep=0.1em,topsep=0.1em}\n\\setlist[enumerate]{leftmargin=1.1em,itemsep=0.1em,topsep=0.1em}\n\\newcommand{\\HR}{\\vspace{0.15em}\\hrule\\vspace{0.25em}}\n\\newlength{\\MyBoxW}\n\\newcommand{\\MyBox}[1]{%\n\\setlength{\\fboxsep}{2.5pt}%\n\\setlength{\\MyBoxW}{\\dimexpr\\linewidth-2\\fboxsep-2\\fboxrule\\relax}%\n\\noindent\\fbox{\\begin{minipage}[t]{\\MyBoxW}\\raggedright #1\\end{minipage}}%\n}\n\\sloppy\n\\emergencystretch=2em',
  E'You are generating a 2-COLUMN PORTRAIT cheat-sheet (physics, maths, or any technical subject).\n\nLAYOUT RULES:\n- Start with a bold title line: {\\Large\\bfseries SUBJECT --- TOPIC \\hfill \\normalsize Cheat-Sheet (2 cols)}\\HR\n- Wrap ALL content in \\begin{multicols}{2} \\footnotesize ... \\end{multicols}\n- Use \\HR (thin horizontal rule) between major sections\n- Use \\textbf{Section Title:} at the start of each section (no \\section command)\n\nCONTENT RULES:\n- Use \\MyBox{...} to highlight key formulas, results, and important definitions\n- Keep text \\footnotesize throughout\n- Equations inline or as short display math — no wide multi-line derivations\n- Pack as much content as possible\n- End with: \\begin{flushright}\\footnotesize \\textit{made with BetterNotes-AI}\\end{flushright}',
  E'\\begin{document}\n\\pagestyle{empty}\n% FILL: Bold title line using {\\Large\\bfseries SUBJECT --- TOPIC \\hfill \\normalsize Cheat-Sheet (2 cols)}\\HR\n\n\\begin{multicols}{2}\n\\footnotesize\n\n% FILL: First major section header with \\textbf{Section Name:}\n% FILL: Key formulas and definitions for this section\n\n% FILL: Use \\HR between major sections\n\n% FILL: Important formulas highlighted with \\MyBox{...}\n\n% FILL: Second section with \\textbf{Section Name:}\n% FILL: Key results and equations\n\n\\HR\n\n% FILL: Third section\n% FILL: Use \\begin{itemize} for enumerable facts or properties\n\n% FILL: Continue with 4-6 more sections filling both columns\n% FILL: Each \\MyBox should contain the single most important formula of its section\n\n\\end{multicols}\n\\begin{flushright}\\footnotesize \\textit{made with BetterNotes-AI}\\end{flushright}\n\\end{document}',
  E'\\begin{document}\n\\pagestyle{empty}\n{\\Large\\bfseries Classical Mechanics --- Cheat Sheet \\hfill \\normalsize Cheat-Sheet (2 cols)}\\HR\n\n\\begin{multicols}{2}\n\\footnotesize\n\n\\textbf{Newton''s Laws}\\\\\n1st: $\\sum F = 0 \\Rightarrow a = 0$. \\quad 2nd: $F = ma$. \\quad 3rd: $F_{AB} = -F_{BA}$.\n\n\\HR\n\n\\MyBox{\n\\textbf{Work-Energy Theorem}\\\\\n$W_{net} = \\Delta KE = \\frac{1}{2}mv_f^2 - \\frac{1}{2}mv_i^2$\n}\n\n\\HR\n\n\\textbf{Kinematics (constant a):}\n\\begin{itemize}\n  \\item $v = v_0 + at$\n  \\item $x = x_0 + v_0 t + \\frac{1}{2}at^2$\n\\end{itemize}\n\n\\end{multicols}\n\\begin{flushright}\\footnotesize \\textit{made with BetterNotes-AI}\\end{flushright}\n\\end{document}',
  2
),

-- ─── cornell ────────────────────────────────────────────────
(
  'cornell',
  'Cornell Notes',
  'Classic Cornell note-taking format with wide left margin for cue keywords and summary box at the bottom.',
  false,
  E'\\documentclass[10pt]{article}\n\\usepackage[english]{babel}\n\\usepackage[utf8]{inputenc}\n\\usepackage[T1]{fontenc}\n\\usepackage{amsmath,amsthm,amssymb,amsfonts}\n\\usepackage{lmodern}\n\\usepackage{xcolor}\n\\usepackage{geometry}\n\\geometry{a4paper,portrait,left=5.5cm,right=1cm,top=2.5cm,bottom=2cm,marginparwidth=4.5cm,marginparsep=0.5cm}\n\\usepackage{fancyhdr}\n\\usepackage{tcolorbox}\n\\usepackage{titlesec}\n\\usepackage{enumitem}\n\\setlength{\\parindent}{0pt}\n\\setlength{\\parskip}{0.3em}\n\\definecolor{cornellred}{RGB}{179,27,27}\n\\definecolor{cueblue}{RGB}{0,70,140}\n\\definecolor{sectiongreen}{RGB}{0,120,60}\n\\definecolor{defgreen}{RGB}{61,176,0}\n\\definecolor{propblue}{RGB}{0,100,180}\n\\definecolor{thmred}{RGB}{180,0,0}\n\\pagestyle{fancy}\n\\fancyhf{}\n\\renewcommand{\\headrulewidth}{1.5pt}\n\\renewcommand{\\headrule}{\\hbox to\\headwidth{\\color{cornellred}\\leaders\\hrule height \\headrulewidth\\hfill}}\n\\reversemarginpar\n\\newcommand{\\cue}[1]{\\marginpar{\\raggedright\\footnotesize\\textcolor{cueblue}{\\textbf{#1}}}}\n\\newtheoremstyle{cornellstyle}{0pt}{3pt}{\\upshape}{}{\\bfseries}{}{ }{}\n\\theoremstyle{cornellstyle}\n\\newtheorem*{definition}{\\textcolor{defgreen}{Def.}}\n\\newtheorem*{proposition}{\\textcolor{propblue}{Prop.}}\n\\newtheorem*{theorem}{\\textcolor{thmred}{Thm.}}\n\\newtheorem*{corollary}{\\textcolor{thmred}{Cor.}}\n\\newtheorem*{example}{\\textcolor{sectiongreen}{Ex.}}\n\\newtheorem*{remark}{\\textcolor{cueblue}{Rmk.}}\n\\newcommand{\\summary}[1]{%\n\\vfill\n\\begin{tcolorbox}[colback=cornellred!5,colframe=cornellred,title=\\textbf{SUMMARY},fonttitle=\\bfseries\\color{white},coltitle=white,sharp corners,boxrule=1pt,colbacktitle=cornellred]\n\\small #1\n\\end{tcolorbox}%\n}\n\\titleformat{\\section}{\\color{cornellred}\\large\\bfseries}{}{0em}{}[\\vspace{-0.7em}{\\color{cornellred}\\rule{\\linewidth}{0.5pt}}\\vspace{0.3em}]\n\\titleformat{\\subsection}{\\color{sectiongreen}\\bfseries}{}{0em}{}\n\\setlist[itemize]{leftmargin=1.2em,itemsep=0.1em,topsep=0.1em}\n\\setlist[enumerate]{leftmargin=1.2em,itemsep=0.1em,topsep=0.1em}',
  E'You are generating a CORNELL NOTE-TAKING document.\n\nLAYOUT RULES:\n- Set the header: \\fancyhead[L]{\\textbf{\\large SUBJECT --- Topic}} and \\fancyhead[R]{\\textbf{Chapter/Lecture}}\n- Wide LEFT MARGIN (5.5cm) is used for cue keywords via \\cue{...}\n- Main body text goes in the right portion (normal flow)\n- Use \\section{Topic} for major topics (styled with cornellred underline)\n- Use \\subsection{Subtopic} for subsections (styled in sectiongreen)\n\nCONTENT RULES:\n- EVERY paragraph or concept should have a \\cue{question or keyword} in the left margin\n- Use theorem environments: definition, proposition, theorem, corollary, example, remark\n- DO NOT redefine these environments\n- For equations, use align* or equation*\n- At the END of the document, add \\summary{brief summary of key points} using the tcolorbox command\n- End with: \\begin{flushright}\\footnotesize \\textit{made with BetterNotes-AI}\\end{flushright}',
  E'\\begin{document}\n% FILL: Set headers: \\fancyhead[L]{\\textbf{\\large SUBJECT --- Topic}} and \\fancyhead[R]{\\textbf{Chapter/Lecture N}}\n\n% FILL: First major section using \\section{Section Title}\n\n% FILL: \\cue{Key question or keyword for this concept}\n% FILL: Main content — definition, theorem, or explanation using appropriate theorem environment\n\n% FILL: \\cue{Another keyword}\n% FILL: Another concept with equation in align* or equation*\n\n% FILL: \\subsection{Subtopic} for finer subdivisions\n% FILL: \\cue{Cue word} before each paragraph\n\n% FILL: Second major section \\section{...}\n% FILL: Continue with cue + content pairs, 4-8 concepts per section\n\n% FILL: Third section (add as many sections as needed for the topic)\n% FILL: Include examples using \\begin{example} ... \\end{example}\n\n% FILL: \\summary{2-5 bullet points or sentences summarizing the key takeaways of the whole document}\n\\begin{flushright}\\footnotesize \\textit{made with BetterNotes-AI}\\end{flushright}\n\\end{document}',
  E'\\begin{document}\n\\fancyhead[L]{\\textbf{\\large Linear Algebra --- Cornell Notes}}\n\\fancyhead[R]{\\textbf{Chapter 1: Vectors}}\n\n\\section{Vector Spaces}\n\n\\cue{What is a vector space?}\n\\begin{definition}\nA \\textbf{vector space} over $\\mathbb{R}$ is a set $V$ with addition and scalar multiplication satisfying 8 axioms.\n\\end{definition}\n\n\\cue{Key examples?}\n\\begin{example}\n$\\mathbb{R}^n$, polynomials $\\mathcal{P}_n$, continuous functions $C[a,b]$.\n\\end{example}\n\n\\cue{Subspace criterion?}\n\\begin{proposition}\n$W \\subseteq V$ is a subspace iff $\\mathbf{0}\\in W$ and $W$ is closed under $+$ and scalar $\\cdot$.\n\\end{proposition}\n\n\\summary{\n\\textbf{Vector space:} closed under $+$ and $\\cdot$ with 8 axioms. \\textbf{Subspace:} contains $\\mathbf{0}$, closed under both operations.\n}\n\\begin{flushright}\\footnotesize \\textit{made with BetterNotes-AI}\\end{flushright}\n\\end{document}',
  3
),

-- ─── problem_solving ────────────────────────────────────────
(
  'problem_solving',
  'Problem Solving Worksheet',
  'STEM problem set with structured problem/given/solution blocks and boxed answers.',
  false,
  E'\\documentclass[10pt]{article}\n\\usepackage[english]{babel}\n\\usepackage[utf8]{inputenc}\n\\usepackage[T1]{fontenc}\n\\usepackage{enumitem}\n\\usepackage{booktabs}\n\\usepackage{amsmath,amsthm,empheq,amssymb,amsfonts,mathrsfs}\n\\usepackage{lmodern}\n\\usepackage{xcolor}\n\\usepackage{geometry}\n\\geometry{a4paper,portrait,left=8mm,right=8mm,top=8mm,bottom=8mm}\n\\usepackage{multicol}\n\\setlength{\\columnseprule}{0.5pt}\n\\setlength{\\columnsep}{0.5cm}\n\\usepackage{titlesec}\n\\titlespacing{\\section}{0pt}{2pt}{0pt}\n\\titlespacing{\\subsection}{0pt}{2pt}{0pt}\n\\titleformat*{\\section}{\\large\\bfseries}\n\\titleformat*{\\subsection}{\\bfseries}\n\\setlength{\\parindent}{0pt}\n\\pagenumbering{gobble}\n\\definecolor{probblue}{RGB}{0,80,158}\n\\definecolor{datagreen}{RGB}{0,128,64}\n\\definecolor{resultred}{RGB}{180,0,0}\n\\definecolor{checkpurple}{RGB}{100,50,150}\n\\newtheoremstyle{problemstyle}{0pt}{0pt}{\\upshape}{}{\\bfseries}{}{0.5em}{}\n\\theoremstyle{problemstyle}\n\\newtheorem*{problem}{\\textcolor{probblue}{Problem}}\n\\newtheorem*{givendata}{\\textcolor{datagreen}{Given}}\n\\newtheorem*{approach}{\\textcolor{probblue}{Approach}}\n\\newtheorem*{solution}{\\textcolor{probblue}{Solution}}\n\\newcommand{\\result}[1]{%\n\\begin{center}\n\\fcolorbox{resultred}{red!5}{\\parbox{0.9\\linewidth}{\\centering\\textbf{\\textcolor{resultred}{Result:}} #1}}\n\\end{center}\n}\n\\newcommand{\\verify}[1]{\\textcolor{checkpurple}{\\textbf{Check:} \\textit{#1}}}\n\\newcommand{\\HR}{\\vspace{0.15em}\\hrule\\vspace{0.25em}}\n\\setlist[itemize]{leftmargin=1.1em,itemsep=0.1em,topsep=0.1em}\n\\setlist[enumerate]{leftmargin=1.1em,itemsep=0.1em,topsep=0.1em}\n\\sloppy\n\\emergencystretch=2em',
  E'You are generating a PROBLEM SOLVING WORKSHEET for STEM subjects (engineering, physics, maths).\n\nLAYOUT RULES:\n- Start with: {\\Large\\bfseries SUBJECT --- Problem Set \\hfill \\normalsize Practice Sheet}\\HR\n- Wrap content in \\begin{multicols}{2} \\footnotesize ... \\end{multicols}\n- Each problem is a self-contained block separated by \\HR\n\nCONTENT RULES:\n- Structure each problem using the environments: problem, givendata, approach, solution\n- Use \\result{boxed answer} to highlight the final answer\n- Use \\verify{dimensional check or sanity check} after each solution\n- Include realistic numerical values, units, and physical context\n- Use amsmath for all equations\n- Generate 4-8 problems of varying difficulty\n- CRITICAL: Always close \\[ ... \\] or align* BEFORE \\end{solution}. NEVER leave display math open when ending an environment.\n- CRITICAL: NEVER nest display math environments.\n- End with: \\begin{flushright}\\footnotesize \\textit{made with BetterNotes-AI}\\end{flushright}',
  E'\\begin{document}\n\\pagestyle{empty}\n% FILL: Title line: {\\Large\\bfseries SUBJECT --- Problem Set \\hfill \\normalsize Practice Sheet}\\HR\n\n\\begin{multicols}{2}\n\\footnotesize\n\n% FILL: Problem 1 — use \\begin{problem} ... \\end{problem} with a clear problem statement\n% FILL: \\begin{givendata} list the known values with units \\end{givendata}\n% FILL: \\begin{solution} step-by-step derivation ending with the answer \\end{solution}\n% FILL: \\result{Final numerical answer with units}\n% FILL: \\verify{Dimensional check}\n\n\\HR\n\n% FILL: Problem 2 — different concept or difficulty level\n% FILL: Problem 3, 4, 5 (4 to 8 problems total)\n\n\\end{multicols}\n\\begin{flushright}\\footnotesize \\textit{made with BetterNotes-AI}\\end{flushright}\n\\end{document}',
  E'\\begin{document}\n\\pagestyle{empty}\n{\\Large\\bfseries Thermodynamics --- Problem Set \\hfill \\normalsize Practice Sheet}\\HR\n\n\\begin{multicols}{2}\n\\footnotesize\n\n\\begin{problem}\nAn ideal gas undergoes isothermal expansion from $V_1 = 2\\,\\mathrm{L}$ to $V_2 = 6\\,\\mathrm{L}$ at $T = 300\\,\\mathrm{K}$.\n\\end{problem}\n\n\\begin{givendata}\n$V_1 = 2\\,\\mathrm{L}$, $V_2 = 6\\,\\mathrm{L}$, $T = 300\\,\\mathrm{K}$, $n = 1\\,\\mathrm{mol}$\n\\end{givendata}\n\n\\begin{solution}\n$W = nRT\\ln(V_2/V_1) \\approx 2740\\,\\mathrm{J}$\n\\end{solution}\n\n\\result{$W \\approx 2.74\\,\\mathrm{kJ}$}\n\\verify{Units: J \\checkmark}\n\n\\HR\n\n\\end{multicols}\n\\begin{flushright}\\footnotesize \\textit{made with BetterNotes-AI}\\end{flushright}\n\\end{document}',
  4
),

-- ─── zettelkasten ───────────────────────────────────────────
(
  'zettelkasten',
  'Zettelkasten Cards',
  'Knowledge cards in Zettelkasten style — atomic concepts with cross-references and tags.',
  false,
  E'\\documentclass[10pt]{article}\n\\usepackage[english]{babel}\n\\usepackage[utf8]{inputenc}\n\\usepackage[T1]{fontenc}\n\\usepackage{amsmath,amssymb,amsfonts}\n\\usepackage{lmodern}\n\\usepackage{xcolor}\n\\usepackage{geometry}\n\\geometry{a4paper,portrait,margin=8mm}\n\\usepackage{tcolorbox}\n\\tcbuselibrary{raster,skins}\n\\setlength{\\parindent}{0pt}\n\\setlength{\\parskip}{0.2em}\n\\definecolor{cardblue}{RGB}{0,80,158}\n\\definecolor{linkpurple}{RGB}{120,50,150}\n\\definecolor{taggreen}{RGB}{0,120,60}\n\\pagenumbering{gobble}\n\\tcbset{\n  zettelstyle/.style={\n    enhanced,sharp corners,\n    colback=white,colframe=cardblue,boxrule=0.8pt,\n    fonttitle=\\bfseries\\small,coltitle=white,colbacktitle=cardblue,\n    attach boxed title to top left={xshift=3mm,yshift=-2mm},\n    boxed title style={sharp corners,colframe=cardblue},\n    top=5mm,bottom=2mm,left=2mm,right=2mm,\n  }\n}\n\\newcommand{\\conn}[1]{\\textcolor{linkpurple}{\\small $\\rightarrow$ \\textit{#1}}}\n\\newcommand{\\tags}[1]{\\par\\vfill\\textcolor{taggreen}{\\scriptsize\\ttfamily #1}}',
  E'You are generating a ZETTELKASTEN KNOWLEDGE CARD document.\n\nLAYOUT RULES:\n- Start with: {\\Large\\bfseries\\color{cardblue} SUBJECT --- Zettelkasten Cards \\hfill \\normalsize Knowledge Atoms}\n- Then: \\vspace{3mm}\\hrule\\vspace{5mm}\n- Each PAGE holds a 2x3 grid of 6 cards using tcbitemize with raster\n- Use: \\begin{tcbitemize}[raster columns=2, raster rows=3, raster height=0.92\\textheight, raster equal height=rows, raster column skip=4mm, raster row skip=4mm]\n\nCONTENT RULES:\n- Each card: \\tcbitem[zettelstyle, title={\\texttt{ID} --- Title}]\n- Card IDs: TOPIC-01, TOPIC-02, etc.\n- Use \\conn{Related Card ID} for cross-references\n- Use \\tags{\\#tag1 \\#tag2} at the bottom of each card\n- Close each page with \\end{tcbitemize} before starting new page\n- Generate at least 6 cards (1 full page)\n- End with: \\begin{flushright}\\footnotesize \\textit{made with BetterNotes-AI}\\end{flushright}',
  E'\\begin{document}\n% FILL: Header: {\\Large\\bfseries\\color{cardblue} SUBJECT --- Zettelkasten Cards \\hfill \\normalsize Knowledge Atoms}\n\\vspace{3mm}\\hrule\\vspace{5mm}\n\n\\begin{tcbitemize}[\n  raster columns=2, raster rows=3,\n  raster height=0.92\\textheight,\n  raster equal height=rows,\n  raster column skip=4mm, raster row skip=4mm,\n]\n\n% FILL: Card 1 — \\tcbitem[zettelstyle, title={\\texttt{TOPIC-01} --- Concept Name}]\n% FILL: \\footnotesize definition or explanation\n% FILL: \\conn{TOPIC-02 Related}\n% FILL: \\tags{\\#tag1 \\#tag2}\n\n% FILL: Cards 2-6 following the same pattern\n\n\\end{tcbitemize}\n\\begin{flushright}\\footnotesize \\textit{made with BetterNotes-AI}\\end{flushright}\n\\end{document}',
  E'\\begin{document}\n{\\Large\\bfseries\\color{cardblue} Graph Theory --- Zettelkasten Cards \\hfill \\normalsize Knowledge Atoms}\n\\vspace{3mm}\\hrule\\vspace{5mm}\n\n\\begin{tcbitemize}[\n  raster columns=2, raster rows=3,\n  raster height=0.92\\textheight,\n  raster equal height=rows,\n  raster column skip=4mm, raster row skip=4mm,\n]\n\n\\tcbitem[zettelstyle, title={\\texttt{GT-01} --- Graph Definition}]\n\\footnotesize\nA \\textbf{graph} $G = (V, E)$ with vertices $V$ and edges $E$.\n\\conn{GT-02 Degree}\n\\tags{\\#graph \\#definition}\n\n\\tcbitem[zettelstyle, title={\\texttt{GT-02} --- Vertex Degree}]\n\\footnotesize\n$\\sum_{v \\in V} \\deg(v) = 2|E|$\n\\conn{GT-01 Graph}\n\\tags{\\#degree \\#graph}\n\n\\end{tcbitemize}\n\\begin{flushright}\\footnotesize \\textit{made with BetterNotes-AI}\\end{flushright}\n\\end{document}',
  5
),

-- ─── study_form ─────────────────────────────────────────────
(
  'study_form',
  'Study Form (High Density)',
  'A4 portrait with 3 very compact columns — formula boxes, constants tables, and property lists for exams.',
  false,
  E'\\documentclass[9pt]{article}\n\\usepackage[utf8]{inputenc}\n\\usepackage[T1]{fontenc}\n\\usepackage{amsmath,amssymb,amsfonts}\n\\usepackage{lmodern}\n\\usepackage{microtype}\n\\usepackage{xcolor}\n\\usepackage{geometry}\n\\geometry{a4paper,portrait,left=4mm,right=4mm,top=4mm,bottom=4mm}\n\\usepackage{multicol}\n\\setlength{\\columnseprule}{0.4pt}\n\\setlength{\\columnsep}{3mm}\n\\usepackage{booktabs}\n\\usepackage{array}\n\\usepackage{enumitem}\n\\setlist[itemize]{noitemsep,topsep=0pt,leftmargin=*,label=\\textbullet}\n\\setlist[enumerate]{noitemsep,topsep=0pt,leftmargin=*}\n\\setlength{\\parindent}{0pt}\n\\setlength{\\parskip}{0pt}\n\\pagenumbering{gobble}\n\\linespread{0.88}\n\\definecolor{headblue}{RGB}{0,60,120}\n\\definecolor{boxbg}{RGB}{240,245,255}\n\\definecolor{tablehead}{RGB}{220,230,245}\n\\newcommand{\\sectionbar}[1]{%\n  {\\color{headblue}\\rule{\\linewidth}{0.6pt}}\\\\\n  {\\footnotesize\\bfseries\\color{headblue} #1}\\\\\n  {\\color{headblue}\\rule{\\linewidth}{0.3pt}}\\vspace{1pt}\n}\n\\newcommand{\\formulabox}[2]{%\n  \\setlength{\\fboxsep}{1.5pt}%\n  \\noindent\\colorbox{boxbg}{%\n    \\parbox{\\dimexpr\\linewidth-3pt}{%\n      \\scriptsize\\textbf{#1:}\\; $#2$%\n    }%\n  }\\vspace{1pt}%\n}\n\\newcommand{\\HR}{\\vspace{1pt}\\hrule\\vspace{2pt}}',
  E'You are generating a HIGH-DENSITY STUDY FORM for physics, maths, or engineering.\n\nLAYOUT RULES:\n- Start with: {\\small\\bfseries\\color{headblue} SUBJECT --- TOPIC \\hfill Study Form}\\HR\n- Wrap ALL content in \\begin{multicols}{3} \\scriptsize ... \\end{multicols}\n- Use \\sectionbar{Section Name} for each major topic\n- Use \\formulabox{Name}{formula} for individual formulas\n- Use tabular environments for constants tables\n\nCONTENT RULES:\n- Constants and values: small tabular (2-3 columns, no captions)\n- Lists of properties with \\begin{itemize}: each item ≤ 1 line\n- Equations: inline or very short display math\n- Pack maximum content — this is a closed-book reference\n- End with: \\begin{flushright}\\tiny\\textit{made with BetterNotes-AI}\\end{flushright}',
  E'\\begin{document}\n% FILL: Title: {\\small\\bfseries\\color{headblue} SUBJECT --- TOPIC \\hfill Study Form}\\HR\n\n\\begin{multicols}{3}\n\\scriptsize\n\n% FILL: \\sectionbar{First Major Topic}\n% FILL: \\formulabox{Formula Name}{latex expression} for each key formula (3-6 per section)\n% FILL: Small constants table with \\begin{tabular}{ll} ... \\end{tabular}\n% FILL: \\begin{itemize} for key properties or rules\n\n\\HR\n\n% FILL: \\sectionbar{Second Major Topic}\n% FILL: More \\formulabox entries\n\n% FILL: Add 4-8 sections total, filling all 3 columns densely\n\n\\end{multicols}\n\\begin{flushright}\\tiny\\textit{made with BetterNotes-AI}\\end{flushright}\n\\end{document}',
  E'\\begin{document}\n{\\small\\bfseries\\color{headblue} Electromagnetism --- Study Form \\hfill Study Form}\\HR\n\n\\begin{multicols}{3}\n\\scriptsize\n\n\\sectionbar{Maxwell''s Equations}\n\\formulabox{Gauss E}{\\nabla\\cdot\\mathbf{E} = \\rho/\\varepsilon_0}\n\\formulabox{Faraday}{\\nabla\\times\\mathbf{E} = -\\partial\\mathbf{B}/\\partial t}\n\n\\HR\n\n\\sectionbar{Constants}\n\\begin{tabular}{ll}\n$\\varepsilon_0$ & $8.85\\times10^{-12}$ F/m \\\\\n$c$ & $3\\times10^8$ m/s \\\\\n\\end{tabular}\n\n\\end{multicols}\n\\begin{flushright}\\tiny\\textit{made with BetterNotes-AI}\\end{flushright}\n\\end{document}',
  6
),

-- ─── lecture_notes ──────────────────────────────────────────
(
  'lecture_notes',
  'Lecture Notes',
  'Structured multi-page lecture notes with objectives, numbered examples, and a summary box.',
  false,
  E'\\documentclass[11pt]{article}\n\\usepackage[utf8]{inputenc}\n\\usepackage[T1]{fontenc}\n\\usepackage[english]{babel}\n\\usepackage{lmodern}\n\\usepackage{microtype}\n\\usepackage{geometry}\n\\geometry{a4paper,left=22mm,right=22mm,top=22mm,bottom=22mm}\n\\usepackage{amsmath,amsthm,amssymb,amsfonts}\n\\usepackage{xcolor}\n\\usepackage{tcolorbox}\n\\tcbuselibrary{skins,breakable}\n\\usepackage{enumitem}\n\\usepackage{booktabs}\n\\usepackage{titlesec}\n\\usepackage{fancyhdr}\n\\setlength{\\parindent}{0pt}\n\\setlength{\\parskip}{4pt}\n\\definecolor{accent}{RGB}{0,90,170}\n\\definecolor{examplebg}{RGB}{245,250,255}\n\\definecolor{summarybg}{RGB}{255,252,235}\n\\definecolor{warningbg}{RGB}{255,245,245}\n\\titleformat{\\section}{\\large\\bfseries\\color{accent}}{\\thesection.}{0.5em}{}[{\\color{accent}\\rule{\\linewidth}{0.4pt}}]\n\\titleformat{\\subsection}{\\bfseries\\color{accent!80!black}}{\\thesubsection.}{0.5em}{}\n\\titlespacing{\\section}{0pt}{8pt}{4pt}\n\\titlespacing{\\subsection}{0pt}{5pt}{2pt}\n\\pagestyle{fancy}\n\\fancyhf{}\n\\renewcommand{\\headrulewidth}{0.4pt}\n\\fancyhead[L]{\\small\\textit{\\leftmark}}\n\\fancyhead[R]{\\small\\textit{BetterNotes}}\n\\fancyfoot[C]{\\small\\thepage}\n\\newcounter{example}[section]\n\\renewcommand{\\theexample}{\\thesection.\\arabic{example}}\n\\newenvironment{example}[1][]{%\n  \\refstepcounter{example}%\n  \\begin{tcolorbox}[\n    enhanced,breakable,\n    colback=examplebg,colframe=accent,\n    title=\\textbf{Example \\theexample\\ifx\\relax#1\\relax\\else: #1\\fi},\n    fonttitle=\\bfseries\\small,\n    coltitle=white,colbacktitle=accent,\n    sharp corners=south,boxrule=0.6pt,\n    top=4pt,bottom=4pt,left=6pt,right=6pt,\n  ]\n}{\\end{tcolorbox}}\n\\newenvironment{keypoint}[1][Key Point]{%\n  \\begin{tcolorbox}[\n    enhanced,breakable,\n    colback=summarybg,colframe=orange!70!black,\n    title=\\textbf{#1},fonttitle=\\bfseries\\small,\n    coltitle=white,colbacktitle=orange!70!black,\n    sharp corners,boxrule=0.6pt,\n    top=3pt,bottom=3pt,left=5pt,right=5pt,\n  ]\n}{\\end{tcolorbox}}\n\\newenvironment{warning}[1][Note]{%\n  \\begin{tcolorbox}[\n    enhanced,colback=warningbg,colframe=red!60!black,\n    title=\\textbf{#1},fonttitle=\\bfseries\\small,\n    coltitle=white,colbacktitle=red!60!black,\n    sharp corners,boxrule=0.6pt,\n    top=3pt,bottom=3pt,left=5pt,right=5pt,\n  ]\n}{\\end{tcolorbox}}\n\\theoremstyle{plain}\n\\newtheorem{theorem}{Theorem}[section]\n\\newtheorem{lemma}[theorem]{Lemma}\n\\newtheorem{proposition}[theorem]{Proposition}\n\\newtheorem{corollary}[theorem]{Corollary}\n\\theoremstyle{definition}\n\\newtheorem{definition}[theorem]{Definition}\n\\theoremstyle{remark}\n\\newtheorem{remark}[theorem]{Remark}\n\\setlist[itemize]{itemsep=2pt,topsep=2pt}\n\\setlist[enumerate]{itemsep=2pt,topsep=2pt}',
  E'You are generating STRUCTURED LECTURE NOTES for a university-level course.\n\nDOCUMENT STRUCTURE:\n1. Title block: \\title + \\author + \\date + \\maketitle\n2. Learning objectives box: \\begin{keypoint}[Learning Objectives] ... \\end{keypoint}\n3. Multiple sections (\\section{}) covering the topic\n4. Numbered examples: \\begin{example}[Title] ... \\end{example}\n5. Theorems and definitions using the defined environments\n6. Warning boxes: \\begin{warning}[Note] ... \\end{warning}\n7. Final Summary section with \\begin{keypoint}[Summary] ... \\end{keypoint}\n\nCONTENT RULES:\n- Write thorough, educational content\n- Each section: 2-4 paragraphs plus examples\n- At least 3-5 examples total\n- Include derivations in align* or equation environments\n- Use \\begin{definition} for formal definitions and \\begin{theorem} for key results\n- Minimum 3 sections of substantial content\n- End with: \\begin{flushright}\\footnotesize \\textit{made with BetterNotes-AI}\\end{flushright}',
  E'\\begin{document}\n% FILL: \\title{Subject: Topic Title}\n% FILL: \\author{Course / Semester}\n% FILL: \\date{\\today}\n\\maketitle\n\n\\begin{keypoint}[Learning Objectives]\n% FILL: \\begin{enumerate} with 3-5 specific learning objectives\n\\end{keypoint}\n\n\\section{First Major Section Title}\n% FILL: Introductory paragraph\n% FILL: \\begin{definition} ... \\end{definition}\n% FILL: \\begin{example}[Title] worked example \\end{example}\n\n\\section{Second Major Section Title}\n% FILL: \\begin{theorem}[Name] ... \\end{theorem}\n% FILL: \\begin{proof} ... \\end{proof}\n% FILL: \\begin{example} ... \\end{example}\n% FILL: \\begin{warning}[Common Mistake] ... \\end{warning}\n\n\\section{Summary}\n\\begin{keypoint}[Summary]\n% FILL: Key takeaways as \\begin{itemize}\n\\end{keypoint}\n\n\\begin{flushright}\\footnotesize \\textit{made with BetterNotes-AI}\\end{flushright}\n\\end{document}',
  E'\\begin{document}\n\\title{Linear Algebra: Eigenvalues and Eigenvectors}\n\\author{Mathematics for Engineers --- Semester 2}\n\\date{\\today}\n\\maketitle\n\n\\begin{keypoint}[Learning Objectives]\n\\begin{enumerate}\n  \\item Define eigenvalues and eigenvectors.\n  \\item Compute eigenvalues via the characteristic polynomial.\n\\end{enumerate}\n\\end{keypoint}\n\n\\section{Definitions}\n\n\\begin{definition}\nLet $A \\in \\mathbb{R}^{n\\times n}$. A scalar $\\lambda$ is an \\textbf{eigenvalue} if $A\\mathbf{v} = \\lambda\\mathbf{v}$ for some non-zero $\\mathbf{v}$.\n\\end{definition}\n\n\\section{Summary}\n\\begin{keypoint}[Summary]\n\\begin{itemize}\n  \\item Eigenvalues satisfy $\\det(A - \\lambda I) = 0$.\n\\end{itemize}\n\\end{keypoint}\n\n\\begin{flushright}\\footnotesize \\textit{made with BetterNotes-AI}\\end{flushright}\n\\end{document}',
  7
),

-- ─── academic_paper ─────────────────────────────────────────
(
  'academic_paper',
  'Academic Paper',
  'Two-column AMS/Physical Review style paper with abstract, theorems, and bibliography.',
  true,
  E'\\documentclass[11pt,twocolumn]{article}\n\\usepackage[english]{babel}\n\\usepackage[utf8]{inputenc}\n\\usepackage[T1]{fontenc}\n\\usepackage{lmodern}\n\\usepackage{microtype}\n\\usepackage{geometry}\n\\geometry{a4paper,left=18mm,right=18mm,top=20mm,bottom=25mm,columnsep=8mm}\n\\usepackage{xcolor}\n\\usepackage{amsmath,amsthm,amssymb,amsfonts,mathtools}\n\\usepackage{bm}\n\\usepackage{graphicx}\n\\usepackage{float}\n\\usepackage{booktabs}\n\\usepackage{array}\n\\usepackage{multirow}\n\\usepackage[numbers,sort&compress]{natbib}\n\\usepackage{hyperref}\n\\hypersetup{colorlinks=true,linkcolor=blue!70!black,citecolor=green!50!black,urlcolor=blue!60!black}\n\\usepackage{titlesec}\n\\titleformat{\\section}{\\large\\bfseries}{\\thesection.}{0.5em}{}\n\\titleformat{\\subsection}{\\bfseries}{\\thesubsection.}{0.5em}{}\n\\setlength{\\parindent}{1em}\n\\setlength{\\parskip}{0pt}\n\\theoremstyle{plain}\n\\newtheorem{theorem}{Theorem}[section]\n\\newtheorem{lemma}[theorem]{Lemma}\n\\newtheorem{proposition}[theorem]{Proposition}\n\\newtheorem{corollary}[theorem]{Corollary}\n\\theoremstyle{definition}\n\\newtheorem{definition}[theorem]{Definition}\n\\newtheorem{example}[theorem]{Example}\n\\theoremstyle{remark}\n\\newtheorem{remark}[theorem]{Remark}\n\\newcommand{\\dd}{\\mathrm{d}}\n\\newcommand{\\avg}[1]{\\langle #1 \\rangle}\n\\newcommand{\\Tr}{\\mathrm{Tr}}\n\\newcommand{\\order}[1]{\\mathcal{O}\\left( #1 \\right)}',
  E'You are generating an ACADEMIC RESEARCH PAPER (two-column, AMS/Physical Review style).\n\nSTRUCTURE:\n1. \\title{} \\author{} \\date{} \\maketitle\n2. \\begin{abstract} ... \\end{abstract}\n3. \\section{Introduction}\n4. \\section{Background} or \\section{Related Work}\n5. \\section{Methods} / \\section{Theory}\n6. \\section{Results}\n7. \\section{Discussion}\n8. \\section{Conclusion}\n9. \\bibliographystyle{unsrtnat} and \\begin{thebibliography}{99} ... \\end{thebibliography}\n\nCONTENT RULES:\n- Use numbered theorem environments: theorem, lemma, proposition, corollary, definition\n- Proofs: \\begin{proof} ... \\end{proof}\n- Use booktabs for tables\n- Citations: \\cite{key}\n- End with: \\begin{flushright}\\footnotesize \\textit{made with BetterNotes-AI}\\end{flushright}',
  E'\\begin{document}\n% FILL: \\title{Full paper title}\n% FILL: \\author{Author Name \\\\ Institution}\n% FILL: \\date{\\today}\n\\maketitle\n\n\\begin{abstract}\n% FILL: 150-250 word abstract with key result and numbers\n\\end{abstract}\n\n\\section{Introduction}\n% FILL: Motivation, context, contributions\n\n\\section{Methods}\n% FILL: Key equations, theorem statement\n\n\\section{Results}\n% FILL: \\begin{theorem} ... \\end{theorem} with \\begin{proof} ... \\end{proof}\n\n\\section{Conclusion}\n% FILL: Summary and future work\n\n\\bibliographystyle{unsrtnat}\n\\begin{thebibliography}{99}\n% FILL: 4-8 references\n\\end{thebibliography}\n\\begin{flushright}\\footnotesize \\textit{made with BetterNotes-AI}\\end{flushright}\n\\end{document}',
  E'\\begin{document}\n\\title{On the Convergence of Stochastic Gradient Methods}\n\\author{A. Author\\\\Department of Mathematics}\n\\date{\\today}\n\\maketitle\n\n\\begin{abstract}\nWe study convergence of SGD. Main result: $\\mathcal{O}(1/\\sqrt{T})$ rate for non-convex objectives.\n\\end{abstract}\n\n\\section{Introduction}\nSGD \\cite{robbins1951} is the workhorse of modern machine learning...\n\n\\begin{theorem}[Convergence Rate]\n$\\frac{1}{T}\\sum_{t=1}^T \\mathbb{E}[\\|\\nabla f(x_t)\\|^2] \\leq \\frac{C}{\\sqrt{T}}$\n\\end{theorem}\n\n\\bibliographystyle{unsrtnat}\n\\begin{thebibliography}{99}\n\\bibitem{robbins1951} H. Robbins and S. Monro, \\textit{Ann. Math. Stat.}, 1951.\n\\end{thebibliography}\n\\begin{flushright}\\footnotesize \\textit{made with BetterNotes-AI}\\end{flushright}\n\\end{document}',
  8
),

-- ─── lab_report ─────────────────────────────────────────────
(
  'lab_report',
  'Lab Report',
  'Technical lab report with setup, data tables with uncertainties, error analysis, and conclusion.',
  true,
  E'\\documentclass[11pt]{article}\n\\usepackage[english]{babel}\n\\usepackage[utf8]{inputenc}\n\\usepackage[T1]{fontenc}\n\\usepackage{lmodern}\n\\usepackage{geometry}\n\\geometry{a4paper,left=25mm,right=25mm,top=25mm,bottom=25mm}\n\\usepackage{amsmath,amssymb}\n\\usepackage{graphicx}\n\\usepackage{float}\n\\usepackage{booktabs}\n\\usepackage{array}\n\\usepackage{multirow}\n\\usepackage{siunitx}\n\\sisetup{separate-uncertainty=true}\n\\usepackage{xcolor}\n\\usepackage{hyperref}\n\\hypersetup{colorlinks=true,linkcolor=blue,urlcolor=blue}\n\\usepackage{titlesec}\n\\titleformat{\\section}{\\large\\bfseries}{\\thesection.}{0.5em}{}\n\\titleformat{\\subsection}{\\bfseries}{\\thesubsection.}{0.5em}{}\n\\setlength{\\parindent}{1em}\n\\setlength{\\parskip}{3pt}\n\\newcommand{\\mean}[1]{\\ensuremath{\\bar{#1}}}\n\\newcommand{\\uncertainty}[2]{\\ensuremath{(#1 \\pm #2)}}',
  E'You are generating a TECHNICAL LAB REPORT.\n\nSTRUCTURE:\n1. \\title{} \\author{} \\date{} \\maketitle\n2. \\begin{abstract} — experiment, method, key result with numbers \\end{abstract}\n3. \\section{Introduction} — purpose, background equations\n4. \\section{Experimental Setup} — apparatus and procedure\n5. \\section{Data and Results} — tables with siunitx\n6. \\section{Error Analysis} — propagation formulas\n7. \\section{Discussion} — comparison with theory\n8. \\section{Conclusion}\n\nCONTENT RULES:\n- Use \\SI{value}{unit} for all measurements\n- Use booktabs for data tables\n- Include error propagation with partial derivatives\n- CRITICAL: \\SI requires BOTH number AND unit. Use e-notation: \\SI{6.02e-19}{J}\n- NEVER use \\includegraphics\n- End with: \\begin{flushright}\\footnotesize \\textit{made with BetterNotes-AI}\\end{flushright}',
  E'\\begin{document}\n% FILL: \\title{Experiment Title}\n% FILL: \\author{Student Name \\\\ Lab Partner: Name}\n\\maketitle\n\n\\begin{abstract}\n% FILL: Method, key result with uncertainty and units\n\\end{abstract}\n\n\\section{Introduction}\n% FILL: Background equations and purpose\n\n\\section{Data and Results}\n% FILL: \\begin{table}[H] with booktabs using \\SI{}{} for all values\n\n\\section{Error Analysis}\n% FILL: Propagation formula with partial derivatives\n% FILL: Final result: \\uncertainty{value}{uncertainty} \\si{unit}\n\n\\section{Conclusion}\n% FILL: Main result with units and uncertainty\n\n\\begin{flushright}\\footnotesize \\textit{made with BetterNotes-AI}\\end{flushright}\n\\end{document}',
  E'\\begin{document}\n\\title{Measurement of Gravitational Acceleration}\n\\author{Student Name \\\\ Lab Partner: Name}\n\\date{\\today}\n\\maketitle\n\n\\begin{abstract}\nMeasured $g$ using a pendulum: $g = \\SI{9.81 \\pm 0.05}{m/s^2}$.\n\\end{abstract}\n\n\\section{Introduction}\n$T = 2\\pi\\sqrt{L/g}$, giving $g = 4\\pi^2 L/T^2$.\n\n\\section{Error Analysis}\n$\\delta g = g\\sqrt{(\\delta L/L)^2 + (2\\delta T/T)^2}$\n\n\\begin{flushright}\\footnotesize \\textit{made with BetterNotes-AI}\\end{flushright}\n\\end{document}',
  9
),

-- ─── data_analysis ──────────────────────────────────────────
(
  'data_analysis',
  'Data Analysis Report',
  'Statistics or ML report with Python code listings, results tables, and mathematical formulations.',
  true,
  E'\\documentclass[11pt]{article}\n\\usepackage[english]{babel}\n\\usepackage[utf8]{inputenc}\n\\usepackage[T1]{fontenc}\n\\usepackage{lmodern}\n\\usepackage{geometry}\n\\geometry{a4paper,left=25mm,right=25mm,top=25mm,bottom=25mm}\n\\usepackage{amsmath,amssymb}\n\\usepackage{graphicx}\n\\usepackage{float}\n\\usepackage{booktabs}\n\\usepackage{array}\n\\usepackage{multirow}\n\\usepackage{xcolor}\n\\usepackage{listings}\n\\usepackage{hyperref}\n\\hypersetup{colorlinks=true,linkcolor=blue,urlcolor=blue}\n\\usepackage{titlesec}\n\\titleformat{\\section}{\\large\\bfseries}{\\thesection.}{0.5em}{}\n\\titleformat{\\subsection}{\\bfseries}{\\thesubsection.}{0.5em}{}\n\\definecolor{codegray}{rgb}{0.5,0.5,0.5}\n\\definecolor{codepurple}{rgb}{0.58,0,0.82}\n\\definecolor{codegreen}{rgb}{0,0.6,0}\n\\definecolor{backcolor}{rgb}{0.97,0.97,0.97}\n\\lstdefinestyle{pythonstyle}{\n  backgroundcolor=\\color{backcolor},\n  commentstyle=\\color{codegreen},\n  keywordstyle=\\color{blue},\n  numberstyle=\\tiny\\color{codegray},\n  stringstyle=\\color{codepurple},\n  basicstyle=\\ttfamily\\footnotesize,\n  breakatwhitespace=false,breaklines=true,\n  captionpos=b,keepspaces=true,\n  numbers=left,numbersep=5pt,showspaces=false,\n  showstringspaces=false,showtabs=false,tabsize=2,\n  language=Python\n}\n\\lstset{style=pythonstyle}\n\\setlength{\\parindent}{1em}\n\\setlength{\\parskip}{3pt}',
  E'You are generating a DATA ANALYSIS REPORT.\n\nSTRUCTURE:\n1. \\title{} \\author{} \\date{} \\maketitle\n2. \\begin{abstract} — dataset, methods, key findings with numbers \\end{abstract}\n3. \\section{Introduction} — problem statement and dataset\n4. \\section{Exploratory Data Analysis}\n5. \\section{Methods} — formulas and code\n6. \\section{Results} — tables and metrics\n7. \\section{Discussion}\n8. \\section{Conclusion}\n\nCONTENT RULES:\n- Use lstlisting for Python/R code with pythonstyle\n- Use booktabs for results tables\n- Include statistical formulas with realistic numbers\n- End with: \\begin{flushright}\\footnotesize \\textit{made with BetterNotes-AI}\\end{flushright}',
  E'\\begin{document}\n% FILL: \\title{Analysis Title}\n% FILL: \\author{Author Name}\n\\maketitle\n\n\\begin{abstract}\n% FILL: Dataset, methods, key result with numbers\n\\end{abstract}\n\n\\section{Methods}\n% FILL: Loss function or statistical formula with align*\n% FILL: \\begin{lstlisting}[caption={Training code}] ... \\end{lstlisting}\n\n\\section{Results}\n% FILL: \\begin{table}[H] performance metrics with booktabs\n\n\\section{Conclusion}\n% FILL: Summary and future work\n\n\\begin{flushright}\\footnotesize \\textit{made with BetterNotes-AI}\\end{flushright}\n\\end{document}',
  E'\\begin{document}\n\\title{Predicting Student Performance: A Machine Learning Approach}\n\\author{A. Researcher}\n\\date{\\today}\n\\maketitle\n\n\\begin{abstract}\nLogistic regression and random forests. Best model AUC = 0.89.\n\\end{abstract}\n\n\\section{Methods}\n\\[ \\mathcal{L} = -\\frac{1}{n}\\sum_{i=1}^n [y_i\\log\\hat{p}_i + (1-y_i)\\log(1-\\hat{p}_i)] \\]\n\n\\begin{lstlisting}[caption={Model training}]\nfrom sklearn.linear_model import LogisticRegression\nmodel = LogisticRegression(C=1.0)\nmodel.fit(X_train, y_train)\n\\end{lstlisting}\n\n\\begin{flushright}\\footnotesize \\textit{made with BetterNotes-AI}\\end{flushright}\n\\end{document}',
  10
)

ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  is_pro = EXCLUDED.is_pro,
  preamble = EXCLUDED.preamble,
  style_guide = EXCLUDED.style_guide,
  structure_template = EXCLUDED.structure_template,
  structure_example = EXCLUDED.structure_example,
  sort_order = EXCLUDED.sort_order,
  updated_at = now();
